### ISSUE TITLE
404 error when Switching heating operation mode VRC700

### ISSUE THREAD

**Issue by switschel** [signalkraft/mypyllant-component#101]
### Before submitting a new issue

- [x] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

When switching the operation mode in HA on a VRC700 a wrong resource is used:
```
404, message='Resource Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/vrc700/v1/systems/<systemID>/zones/0/heating/operation-mode')
```

I guess it must be `end-user-app-api` instead of `vrc700` in the URL

### Logs

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/mypyllant/climate.py", line 434, in async_set_hvac_mode
    await self.coordinator.api.set_zone_heating_operating_mode(
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 506, in set_zone_heating_operating_mode
    return await self.aiohttp_session.patch(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 691, in _request
    await raise_for_status(resp)
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 102, in on_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Resource Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/vrc700/v1/systems/<systemID>/zones/0/heating/operation-mode')
```

**Comment by signalkraft** [comment]
Could you please test with the latest pre-release? https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.3b6

**Comment by switschel** [comment]
My fault I used reverese engineering again and discovered these URL for operation mode:
The original fault was **"zones**" instead of **"zone**".

```
https://api.vaillant-group.com/service-connected-control/vrc700/v1/systems/<systemId>/zone/0/heating/operation-mode
```
Payload:
```
{
    "operationMode": "DAY"
}
```
operationMode can be "DAY", "AUTO", "NIGHT", "OFF"

Same for cooling but only "DAY", AUTO", "OFF"

**Comment by MrBuff** [comment]
I'm on v0.7.3b but i'm getting the same error:

```
404, message='Resource Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/4df88bb3-c06c-430b-9048-21364ec0fc9a/zone/0/heating/time-windows')
```

**Comment by signalkraft** [comment]
Could you try https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.3b7 please?

**Comment by switschel** [comment]
> Could you try https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.3b7 please?

Fixed it for me. Works fine now!
