### ISSUE TITLE
No entities with Multimatic 700 panel with VR921 gateway

### ISSUE THREAD

**Issue by RobertSorgenfrei** [signalkraft/mypyllant-component#114]
### Before submitting a new issue

- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Hello, after upgrading my AUROCompact heating system with the Multimatic 700 panel and the VR921 gateway from the Multimatic app to the MyVaillant app, the Multimatic integration in Home Assistant of course no longer worked.

Through my search I came across the MyPyllant integration. First I installed version 7.3.0 via HACS. Unfortunately without success. The registration went smoothly, but no entities were displayed to me. Then I updated to version 7.4.0b, but unfortunately that didn’t work either. My MyVaillant account is displayed to me, but I don’t see any entities.

Can anybody help me further?

System as described above: Multimatic 700 panel with VR921 gateway

### Logs

```
2024-02-21 09:30:07.114 DEBUG (MainThread) [custom_components.mypyllant] Starting mypyllant component v0.7.3 (library 0.7.19) with homeassistant 2024.2.1, dacite 1.8.0, and aiohttp 3.9.3
2024-02-21 09:30:07.114 DEBUG (MainThread) [custom_components.mypyllant] Creating API and logging in with xxxxxxxxxxxxxxxxx in realm germany
2024-02-21 09:30:11.691 DEBUG (MainThread) [custom_components.mypyllant] Refreshing SystemCoordinator
2024-02-21 09:30:11.691 DEBUG (MainThread) [custom_components.mypyllant] Starting async update data for SystemCoordinator
2024-02-21 09:30:11.691 DEBUG (MainThread) [custom_components.mypyllant] Waiting 119s until token refresh for xxxxxxxxxxxxxxxxx 
2024-02-21 09:30:11.916 ERROR (MainThread) [custom_components.mypyllant] Unexpected error fetching myVAILLANT data: 'types.UnionType' object has no attribute '__origin__'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/dacite/types.py", line 22, in extract_origin_collection
    return collection.__extra__
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'types.UnionType' object has no attribute '__extra__'. Did you mean: '__str__'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/__init__.py", line 350, in _async_update_data
    data = [
           ^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 327, in get_systems
    async for home in homes:
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 301, in get_homes
    yield Home.from_api(timezone=timezone, **home_json)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 69, in from_api
    return from_dict(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/core.py", line 64, in from_dict
    value = _build_value(type_=field_type, data=field_data, config=config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/core.py", line 101, in _build_value
    if is_subclass(type_, cast_type):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/types.py", line 168, in is_subclass
    if is_generic_collection(sub_type):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/types.py", line 147, in is_generic_collection
    origin = extract_origin_collection(type_)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/types.py", line 24, in extract_origin_collection
    return collection.__origin__
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'types.UnionType' object has no attribute '__origin__'
2024-02-21 09:30:11.922 DEBUG (MainThread) [custom_components.mypyllant] Finished fetching myVAILLANT data in 0.231 seconds (success: False)
2024-02-21 09:30:11.923 DEBUG (MainThread) [custom_components.mypyllant] Refreshing DailyDataCoordinator
2024-02-21 09:30:11.923 DEBUG (MainThread) [custom_components.mypyllant] Starting async update data for DailyDataCoordinator
2024-02-21 09:30:11.923 DEBUG (MainThread) [custom_components.mypyllant] Waiting 119s until token refresh for xxxxxxxxxxxxxxxxx 
2024-02-21 09:30:12.022 ERROR (MainThread) [custom_components.mypyllant] Unexpected error fetching myVAILLANT data: 'types.UnionType' object has no attribute '__origin__'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/dacite/types.py", line 22, in extract_origin_collection
    return collection.__extra__
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'types.UnionType' object has no attribute '__extra__'. Did you mean: '__str__'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/__init__.py", line 379, in _async_update_data
    async for system in await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 327, in get_systems
    async for home in homes:
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 301, in get_homes
    yield Home.from_api(timezone=timezone, **home_json)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 69, in from_api
    return from_dict(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/core.py", line 64, in from_dict
    value = _build_value(type_=field_type, data=field_data, config=config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/core.py", line 101, in _build_value
    if is_subclass(type_, cast_type):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/types.py", line 168, in is_subclass
    if is_generic_collection(sub_type):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/types.py", line 147, in is_generic_collection
    origin = extract_origin_collection(type_)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/types.py", line 24, in extract_origin_collection
    return collection.__origin__
           ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'types.UnionType' object has no attribute '__origin__'
2024-02-21 09:30:12.028 DEBUG (MainThread) [custom_components.mypyllant] Finished fetching myVAILLANT data in 0.105 seconds (success: False)
2024-02-21 09:30:12.029 WARNING (MainThread) [custom_components.mypyllant.binary_sensor] No system data, skipping binary sensors
2024-02-21 09:30:12.029 WARNING (MainThread) [custom_components.mypyllant.calendar] No system data, skipping calendar entities
2024-02-21 09:30:12.030 WARNING (MainThread) [custom_components.mypyllant.climate] No system data, skipping climate
2024-02-21 09:30:12.030 WARNING (MainThread) [custom_components.mypyllant.datetime] No system data, skipping date time entities
2024-02-21 09:30:12.030 WARNING (MainThread) [custom_components.mypyllant.number] No system data, skipping number entities
2024-02-21 09:30:12.030 WARNING (MainThread) [custom_components.mypyllant.sensor] No system data, skipping sensors
2024-02-21 09:30:12.030 DEBUG (MainThread) [custom_components.mypyllant.sensor] Daily data: None
2024-02-21 09:30:12.030 WARNING (MainThread) [custom_components.mypyllant.sensor] No daily data, skipping sensors
2024-02-21 09:30:12.030 WARNING (MainThread) [custom_components.mypyllant.switch] No system data, skipping switch entities
2024-02-21 09:30:12.030 WARNING (MainThread) [custom_components.mypyllant.water_heater] No system data, skipping water heater


```

**Comment by RobertSorgenfrei** [comment]
Found a mistake!!! For me too it was the stupid Govee integration!!! I deleted it and now it works!
