### ISSUE TITLE
Could not get MPC / RTS data

### ISSUE THREAD

**Issue by ThomasBergholdWieser** [signalkraft/mypyllant-component#128]
### Before submitting a new issue

- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [ ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

I get constant warnings in my loggings in a very short intervall. It seems this resources are gone and further checking for them will only continue to pollute the logs

### Logs

```
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 1105, in get_rts
response = await self.aiohttp_session.get(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 691, in _request
await raise_for_status(resp)
File "/usr/local/lib/python3.12/site-packages/myPyllant/http_client.py", line 50, in on_raise_for_status
response.raise_for_status()
File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Resource Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/vrc700/v1/rts/<token removed>/devices')
2024-03-07 10:29:07.047 WARNING (MainThread) [myPyllant.api] Could not get MPC data
```

```
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 1124, in get_mpc
response = await self.aiohttp_session.get(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 691, in _request
await raise_for_status(resp)
File "/usr/local/lib/python3.12/site-packages/myPyllant/http_client.py", line 50, in on_raise_for_status
response.raise_for_status()
File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Resource Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/vrc700/v1/hem/<token removed>/mpc')
2024-03-07 10:30:08.118 WARNING (MainThread) [myPyllant.api] Could not get RTS data
```

**Comment by mike4001** [comment]
I can confirm this.

I saw it happening right after the Home assistant Core 2024.3.0 update, but it´s possible that it is not related.

I just checked logs after the Home Assistant update.

**Comment by Brudertac** [comment]
@signalkraft 

Are there any News on this Problem? 
I have that too. Also for Tests i setup a complete new HAOS (Virtual) and mypyllant cant load any Data (404 Error)

Thanks!

**Comment by JavanXD** [comment]
I would like to re-open this issue. @signalkraft 
Because when I execute `generate_test_data` from the `myPyllant` CLI or from the `mypyllant-component`, it does indeed work, the rts and mpc data gets loaded without a 404 error. I can see the onOffcycles in the output. But in regular usage, when I enable the checkbox in the Configuration setup of the Integration, I also receive the 404 error. I assume that the actual `system.id` / `home.system_id`  /  `get_system_id()` is using a wrong value, that's why there is a 404. The system_id in the error log, is completely different from the system_id from the generate_test_data output. I noticed that you used different parameter names for the system_id which could be refactored.
