### ISSUE TITLE
'AUTO' is not a valid DHWOperationMode (migrated from multimatic)

### ISSUE THREAD

**Issue by thomasgermain** [signalkraft/mypyllant-component#135]
### Before submitting a new issue

- [X] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [X] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [X] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

I guess I'm in the last wave for the migration from multimatic to myVaillant. Anyway I just migrated and I'm playing around :).

I'm trying to set my water heater to `AUTO` (from off), but I get the following error.
I quickly checked into the code, it sounds like `self.domestic_hot_water.control_identifier.is_vrc700` it is not set correctly. I have a VRC700/5.

I can provide you with some API response if needed, if you tell me which endpoint to call :)

### Logs

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2319, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2356, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 905, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 391, in async_handle_set_operation_mode
    await self.async_set_operation_mode(operation_mode)
  File "/config/custom_components/mypyllant/water_heater.py", line 208, in async_set_operation_mode
    DHWOperationMode(enum_value),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 744, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1158, in __new__
    raise ve_exc
ValueError: 'AUTO' is not a valid DHWOperationMode
```

### Data export:

```json
[
  {
    "extra_fields": {
      "continuous_heating_start_setpoint": -26.0,
      "alternative_point": -21.0,
      "heating_circuit_bivalence_point": 0.0,
      "dhw_bivalence_point": -7.0,
      "adaptive_heating_curve": true,
      "dhw_maximum_loading_time": 60,
      "dhw_hysteresis": 5.0,
      "dhw_flow_setpoint_offset": 25.0,
      "max_flow_setpoint_heatpump_error": 25.0,
      "dhw_maximum_temperature": 80.0,
      "hybrid_control_strategy": "BIVALENCE_POINT",
      "paralell_tank_loading_allowed": true,
      "outdoor_temperature": 8.0625,
      "outdoor_temperature_average24h": 10.734375,
      "system_water_pressure": 1.9,
      "legionella_protection_start_weekday": "THURSDAY",
      "energy_manager_state": "HEATING",
      "system_off": false,
      "controller_type": "VRC700",
      "controller_revision": "R5",
      "system_scheme": 1,
      "backup_heater_type": "CONDENSING",
      "backup_heater_allowed_for": "DOMESTIC_HOT_WATER_AND_HEATING",
      "module_configuration_v_r71": 3,
      "energy_provide_power_cut_behavior": "DISABLE_HEATPUMP",
      "smart_photovoltaic_buffer_offset": 10.0,
      "external_energy_management_activation": false
    },
    "id": "...",
    "state": {
      "system": {
        "outdoor_temperature": 8.0625,
        "outdoor_temperature_average24h": 10.734375,
        "system_water_pressure": 1.9,
        "legionella_protection_start_weekday": "THURSDAY",
        "energy_manager_state": "HEATING",
        "system_off": false
      },
      "zones": [
        {
          "index": 0,
          "desired_room_temperature_setpoint_heating": 21.0,
          "desired_room_temperature_setpoint": 21.0,
          "current_special_function": "NONE"
        },
        {
          "index": 1,
          "desired_room_temperature_setpoint_heating": 20.5,
          "desired_room_temperature_setpoint": 20.5,
          "current_room_temperature": 21.0,
          "current_room_humidity": 55.0,
          "current_special_function": "NONE"
        }
      ],
      "circuits": [
        {
          "index": 0,
          "circuit_state": "HEATING",
          "current_circuit_flow_temperature": 47.5,
          "heating_circuit_flow_setpoint": 55.0,
          "calculated_energy_manager_state": "HEATING_ACTIVE"
        },
        {
          "index": 1,
          "circuit_state": "STANDBY",
          "current_circuit_flow_temperature": 34.625,
          "heating_circuit_flow_setpoint": 0.0,
          "calculated_energy_manager_state": "HEATING_STANDBY"
        }
      ],
      "dhw": [
        {
          "index": 255,
          "current_special_function": "NONE",
          "current_dhw_temperature": 50.0
        }
      ]
    },
    "properties": {
      "system": {
        "controller_type": "VRC700",
        "controller_revision": "R5",
        "system_scheme": 1,
        "backup_heater_type": "CONDENSING",
        "backup_heater_allowed_for": "DOMESTIC_HOT_WATER_AND_HEATING",
        "module_configuration_v_r71": 3,
        "energy_provide_power_cut_behavior": "DISABLE_HEATPUMP",
        "smart_photovoltaic_buffer_offset": 10.0,
        "external_energy_management_activation": false
      },
      "zones": [
        {
          "index": 0,
          "is_active": true,
          "zone_binding": "NONE",
          "associated_circuit_index": 0
        },
        {
          "index": 1,
          "is_active": true,
          "zone_binding": "CENTRAL_CONTROL",
          "associated_circuit_index": 1
        }
      ],
      "circuits": [
        {
          "index": 0,
          "mixer_circuit_type_external": "HEATING",
          "heating_circuit_type": "DIRECT_HEATING_CIRCUIT",
          "is_cooling_allowed": false
        },
        {
          "index": 1,
          "mixer_circuit_type_external": "HEATING",
          "heating_circuit_type": "MIXER_CIRCUIT_EXTERNAL",
          "is_cooling_allowed": false
        }
      ],
      "dhw": [
        {
          "index": 255,
          "min_setpoint": 35.0,
          "max_setpoint": 70.0
        }
      ]
    },
    "configuration": {
      "system": {
        "continuous_heating_start_setpoint": -26.0,
        "alternative_point": -21.0,
        "heating_circuit_bivalence_point": 0.0,
        "dhw_bivalence_point": -7.0,
        "adaptive_heating_curve": true,
        "dhw_maximum_loading_time": 60,
        "dhw_hysteresis": 5.0,
        "dhw_flow_setpoint_offset": 25.0,
        "max_flow_setpoint_heatpump_error": 25.0,
        "dhw_maximum_temperature": 80.0,
        "hybrid_control_strategy": "BIVALENCE_POINT",
        "paralell_tank_loading_allowed": true
      },
      "zones": [
        {
          "index": 0,
          "general": {
            "name": "ETAGE     ",
            "holiday_start_date_time": "2015-01-01T00:00:00Z",
            "holiday_end_date_time": "2015-01-01T00:00:00Z",
            "holiday_setpoint": 5.0
          },
          "heating": {
            "operation_mode_heating": "DAY",
            "set_back_temperature": 11.0,
            "day_temperature_heating": 21.0,
            "time_program_heating": {
              "meta_info": {
                "min_slots_per_day": 0,
                "max_slots_per_day": 3,
                "setpoint_required_per_slot": false
              },
              "monday": [],
              "tuesday": [],
              "wednesday": [],
              "thursday": [],
              "friday": [],
              "saturday": [],
              "sunday": []
            }
          },
          "desired_room_temperature_setpoint_heating": 21.0,
          "desired_room_temperature_setpoint": 21.0,
          "current_special_function": "NONE",
          "is_active": true,
          "zone_binding": "NONE",
          "associated_circuit_index": 0
        },
        {
          "index": 1,
          "general": {
            "name": "SALON     ",
            "holiday_start_date_time": "2015-01-01T00:00:00Z",
            "holiday_end_date_time": "2015-01-01T00:00:00Z",
            "holiday_setpoint": 5.0
          },
          "heating": {
            "operation_mode_heating": "AUTO",
            "set_back_temperature": 18.5,
            "day_temperature_heating": 20.5,
            "time_program_heating": {
              "meta_info": {
                "min_slots_per_day": 0,
                "max_slots_per_day": 3,
                "setpoint_required_per_slot": false
              },
              "monday": [
                {
                  "start_time": 320,
                  "end_time": 1080
                }
              ],
              "tuesday": [
                {
                  "start_time": 320,
                  "end_time": 1080
                }
              ],
              "wednesday": [
                {
                  "start_time": 320,
                  "end_time": 1080
                }
              ],
              "thursday": [
                {
                  "start_time": 320,
                  "end_time": 1080
                }
              ],
              "friday": [
                {
                  "start_time": 320,
                  "end_time": 1080
                }
              ],
              "saturday": [
                {
                  "start_time": 320,
                  "end_time": 1080
                }
              ],
              "sunday": [
                {
                  "start_time": 320,
                  "end_time": 1080
                }
              ]
            }
          },
          "desired_room_temperature_setpoint_heating": 20.5,
          "desired_room_temperature_setpoint": 20.5,
          "current_room_temperature": 21.0,
          "current_room_humidity": 55.0,
          "current_special_function": "NONE",
          "is_active": true,
          "zone_binding": "CENTRAL_CONTROL",
          "associated_circuit_index": 1
        }
      ],
      "circuits": [
        {
          "index": 0,
          "heating_curve": 4.0,
          "heating_flow_temperature_minimum_setpoint": 40.0,
          "heating_flow_temperature_maximum_setpoint": 55.0,
          "heat_demand_limited_by_outside_temperature": 24.0,
          "heating_circuit_flow_setpoint_excess_offset": 0.0,
          "setback_mode_enabled": false,
          "room_temperature_control_mode": "THERMOSTAT_FUNCTION",
          "circuit_state": "HEATING",
          "current_circuit_flow_temperature": 47.5,
          "heating_circuit_flow_setpoint": 55.0,
          "calculated_energy_manager_state": "HEATING_ACTIVE",
          "mixer_circuit_type_external": "HEATING",
          "heating_circuit_type": "DIRECT_HEATING_CIRCUIT",
          "is_cooling_allowed": false
        },
        {
          "index": 1,
          "heating_curve": 0.30357337,
          "heating_flow_temperature_minimum_setpoint": 22.0,
          "heating_flow_temperature_maximum_setpoint": 38.0,
          "heat_demand_limited_by_outside_temperature": 21.0,
          "heating_circuit_flow_setpoint_excess_offset": 0.0,
          "setback_mode_enabled": false,
          "room_temperature_control_mode": "THERMOSTAT_FUNCTION",
          "circuit_state": "STANDBY",
          "current_circuit_flow_temperature": 34.625,
          "heating_circuit_flow_setpoint": 0.0,
          "calculated_energy_manager_state": "HEATING_STANDBY",
          "mixer_circuit_type_external": "HEATING",
          "heating_circuit_type": "MIXER_CIRCUIT_EXTERNAL",
          "is_cooling_allowed": false
        }
      ],
      "dhw": [
        {
          "index": 255,
          "operation_mode_dhw": "AUTO",
          "tapping_setpoint": 55.0,
          "holiday_start_date_time": "2015-01-01T00:00:00Z",
          "holiday_end_date_time": "2015-01-01T00:00:00Z",
          "time_program_dhw": {
            "meta_info": {
              "min_slots_per_day": 0,
              "max_slots_per_day": 3,
              "setpoint_required_per_slot": false
            },
            "monday": [
              {
                "start_time": 330,
                "end_time": 360
              },
              {
                "start_time": 1050,
                "end_time": 1090
              }
            ],
            "tuesday": [
              {
                "start_time": 330,
                "end_time": 360
              },
              {
                "start_time": 1050,
                "end_time": 1090
              }
            ],
            "wednesday": [
              {
                "start_time": 330,
                "end_time": 360
              },
              {
                "start_time": 1050,
                "end_time": 1090
              }
            ],
            "thursday": [
              {
                "start_time": 330,
                "end_time": 360
              },
              {
                "start_time": 1050,
                "end_time": 1090
              }
            ],
            "friday": [
              {
                "start_time": 330,
                "end_time": 360
              },
              {
                "start_time": 1050,
                "end_time": 1090
              }
            ],
            "saturday": [
              {
                "start_time": 330,
                "end_time": 360
              },
              {
                "start_time": 1050,
                "end_time": 1090
              }
            ],
            "sunday": [
              {
                "start_time": 330,
                "end_time": 360
              },
              {
                "start_time": 1050,
                "end_time": 1090
              }
            ]
          },
          "time_program_circulation_pump": {
            "meta_info": {
              "min_slots_per_day": 0,
              "max_slots_per_day": 3,
              "setpoint_required_per_slot": false
            },
            "monday": [],
            "tuesday": [],
            "wednesday": [],
            "thursday": [],
            "friday": [],
            "saturday": [],
            "sunday": []
          },
          "current_special_function": "NONE",
          "current_dhw_temperature": 50.0,
          "min_setpoint": 35.0,
          "max_setpoint": 70.0
        }
      ]
    },
    "home": {
      "extra_fields": {
        "migration_finished_at": "2024-03-15T09:40:07.807377922Z",
        "online_state": "ONLINE"
      },
      "country_code": "BE",
      "timezone": "tzfile('/usr/share/zoneinfo/Europe/Brussels')",
      "nomenclature": "VR 920",
      "serial_number": "...",
      "state": "CLAIMED",
      "system_id": "...",
      "home_name": "Maison",
      "address": {
        "street": "...",
        "extension": null,
        "city": "...",
        "postal_code": "...",
        "country_code": "BE"
      },
      "product_information": "VR920",
      "migration_state": "FINISHED",
      "cag": false,
      "firmware_version": "0357.40.34",
      "firmware": {
        "version": "0357.40.34",
        "update_enabled": false,
        "update_required": false
      },
      "product_metadata": {
        "product_type": "VR920",
        "production_year": "17",
        "production_week": "48",
        "article_number": "..."
      }
    },
    "brand": "vaillant",
    "timezone": "tzfile('/usr/share/zoneinfo/Europe/Brussels')",
    "control_identifier": "vrc700",
    "connected": true,
    "diagnostic_trouble_codes": [
      {
        "serial_number": "...",
        "article_number": "...",
        "codes": []
      },
      {
        "serial_number": "...",
        "article_number": "...",
        "codes": []
      },
      {
        "serial_number": "...",
        "article_number": "...",
        "codes": []
      },
      {
        "serial_number": "...",
        "article_number": "...",
        "codes": []
      }
    ],
    "current_system": {
      "system_type": "UNKNOWN",
      "has_emf_capable_devices": true,
      "primary_heat_generator": null,
      "secondary_heat_generators": [],
      "electric_backup_heater": null,
      "solar_station": null,
      "ventilation": null,
      "gateway": null
    },
    "zones": [
      {
        "extra_fields": {},
        "system_id": "4fe630fa-7c07-48c5-af29-0e48a4c1a843",
        "general": {
          "extra_fields": {
            "holiday_setpoint": 5.0
          },
          "name": "ETAGE     ",
          "timezone": "tzfile('/usr/share/zoneinfo/Europe/Brussels')",
          "holiday_start_date_time": "2015-01-01 00:00:00+00:00",
          "holiday_end_date_time": "2015-01-01 00:00:00+00:00"
        },
        "timezone": "tzfile('/usr/share/zoneinfo/Europe/Brussels')",
        "control_identifier": "vrc700",
        "index": 0,
        "zone_binding": "NONE",
        "heating": {
          "extra_fields": {},
          "control_identifier": "vrc700",
          "operation_mode_heating": "DAY",
          "time_program_heating": {
            "extra_fields": {},
            "monday": [],
            "tuesday": [],
            "wednesday": [],
            "thursday": [],
            "friday": [],
            "saturday": [],
            "sunday": [],
            "meta_info": {
              "min_slots_per_day": 0,
              "max_slots_per_day": 3,
              "setpoint_required_per_slot": false
            }
          },
          "set_back_temperature": 11.0,
          "manual_mode_setpoint_heating": null,
          "day_temperature_heating": 21.0
        },
        "current_special_function": "NONE",
        "is_active": true,
        "heating_state": null,
        "is_cooling_allowed": null,
        "cooling": null,
        "current_room_temperature": null,
        "desired_room_temperature_setpoint_heating": 21.0,
        "desired_room_temperature_setpoint_cooling": null,
        "desired_room_temperature_setpoint": 21.0,
        "current_room_humidity": null,
        "associated_circuit_index": 0,
        "quick_veto_start_date_time": null,
        "quick_veto_end_date_time": null
      },
      {
        "extra_fields": {},
        "system_id": "...",
        "general": {
          "extra_fields": {
            "holiday_setpoint": 5.0
          },
          "name": "SALON     ",
          "timezone": "tzfile('/usr/share/zoneinfo/Europe/Brussels')",
          "holiday_start_date_time": "2015-01-01 00:00:00+00:00",
          "holiday_end_date_time": "2015-01-01 00:00:00+00:00"
        },
        "timezone": "tzfile('/usr/share/zoneinfo/Europe/Brussels')",
        "control_identifier": "vrc700",
        "index": 1,
        "zone_binding": "CENTRAL_CONTROL",
        "heating": {
          "extra_fields": {},
          "control_identifier": "vrc700",
          "operation_mode_heating": "AUTO",
          "time_program_heating": {
            "extra_fields": {},
            "monday": [
              {
                "extra_fields": {},
                "index": 0,
                "weekday_name": "monday",
                "start_time": 320,
                "end_time": 1080,
                "setpoint": null
              }
            ],
            "tuesday": [
              {
                "extra_fields": {},
                "index": 0,
                "weekday_name": "tuesday",
                "start_time": 320,
                "end_time": 1080,
                "setpoint": null
              }
            ],
            "wednesday": [
              {
                "extra_fields": {},
                "index": 0,
                "weekday_name": "wednesday",
                "start_time": 320,
                "end_time": 1080,
                "setpoint": null
              }
            ],
            "thursday": [
              {
                "extra_fields": {},
                "index": 0,
                "weekday_name": "thursday",
                "start_time": 320,
                "end_time": 1080,
                "setpoint": null
              }
            ],
            "friday": [
              {
                "extra_fields": {},
                "index": 0,
                "weekday_name": "friday",
                "start_time": 320,
                "end_time": 1080,
                "setpoint": null
              }
            ],
            "saturday": [
              {
                "extra_fields": {},
                "index": 0,
                "weekday_name": "saturday",
                "start_time": 320,
                "end_time": 1080,
                "setpoint": null
              }
            ],
            "sunday": [
              {
                "extra_fields": {},
                "index": 0,
                "weekday_name": "sunday",
                "start_time": 320,
                "end_time": 1080,
                "setpoint": null
              }
            ],
            "meta_info": {
              "min_slots_per_day": 0,
              "max_slots_per_day": 3,
              "setpoint_required_per_slot": false
            }
          },
          "set_back_temperature": 18.5,
          "manual_mode_setpoint_heating": null,
          "day_temperature_heating": 20.5
        },
        "current_special_function": "NONE",
        "is_active": true,
        "heating_state": null,
        "is_cooling_allowed": null,
        "cooling": null,
        "current_room_temperature": 21.0,
        "desired_room_temperature_setpoint_heating": 20.5,
        "desired_room_temperature_setpoint_cooling": null,
        "desired_room_temperature_setpoint": 20.5,
        "current_room_humidity": 55.0,
        "associated_circuit_index": 1,
        "quick_veto_start_date_time": null,
        "quick_veto_end_date_time": null
      }
    ],
    "circuits": [
      {
        "extra_fields": {
          "timezone": "tzfile('/usr/share/zoneinfo/Europe/Brussels')",
          "heat_demand_limited_by_outside_temperature": 24.0,
          "room_temperature_control_mode": "THERMOSTAT_FUNCTION",
          "heating_circuit_type": "DIRECT_HEATING_CIRCUIT",
          "setback_mode_enabled": false,
          "heating_circuit_flow_setpoint": 55.0,
          "heating_circuit_flow_setpoint_excess_offset": 0.0
        },
        "system_id": "...",
        "index": 0,
        "circuit_state": "HEATING",
        "mixer_circuit_type_external": "HEATING",
        "set_back_mode_enabled": null,
        "zones": [],
        "is_cooling_allowed": false,
        "current_circuit_flow_temperature": 47.5,
        "heating_curve": 4.0,
        "heating_flow_temperature_minimum_setpoint": 40.0,
        "heating_flow_temperature_maximum_setpoint": 55.0,
        "min_flow_temperature_setpoint": null,
        "calculated_energy_manager_state": "HEATING_ACTIVE"
      },
      {
        "extra_fields": {
          "timezone": "tzfile('/usr/share/zoneinfo/Europe/Brussels')",
          "heat_demand_limited_by_outside_temperature": 21.0,
          "room_temperature_control_mode": "THERMOSTAT_FUNCTION",
          "heating_circuit_type": "MIXER_CIRCUIT_EXTERNAL",
          "setback_mode_enabled": false,
          "heating_circuit_flow_setpoint": 0.0,
          "heating_circuit_flow_setpoint_excess_offset": 0.0
        },
        "system_id": "...",
        "index": 1,
        "circuit_state": "STANDBY",
        "mixer_circuit_type_external": "HEATING",
        "set_back_mode_enabled": null,
        "zones": [],
        "is_cooling_allowed": false,
        "current_circuit_flow_temperature": 34.625,
        "heating_curve": 0.30357337,
        "heating_flow_temperature_minimum_setpoint": 22.0,
        "heating_flow_temperature_maximum_setpoint": 38.0,
        "min_flow_temperature_setpoint": null,
        "calculated_energy_manager_state": "HEATING_STANDBY"
      }
    ],
    "domestic_hot_water": [
      {
        "extra_fields": {
          "timezone": "tzfile('/usr/share/zoneinfo/Europe/Brussels')",
          "holiday_end_date_time": "2015-01-01T00:00:00Z",
          "holiday_start_date_time": "2015-01-01T00:00:00Z"
        },
        "system_id": "...",
        "index": 255,
        "control_identifier": "vrc700",
        "current_special_function": "NONE",
        "max_setpoint": 70.0,
        "min_setpoint": 35.0,
        "operation_mode_dhw": "AUTO",
        "time_program_dhw": {
          "extra_fields": {},
          "monday": [
            {
              "extra_fields": {},
              "index": 0,
              "weekday_name": "monday",
              "start_time": 330,
              "end_time": 360
            },
            {
              "extra_fields": {},
              "index": 1,
              "weekday_name": "monday",
              "start_time": 1050,
              "end_time": 1090
            }
          ],
          "tuesday": [
            {
              "extra_fields": {},
              "index": 0,
              "weekday_name": "tuesday",
              "start_time": 330,
              "end_time": 360
            },
            {
              "extra_fields": {},
              "index": 1,
              "weekday_name": "tuesday",
              "start_time": 1050,
              "end_time": 1090
            }
          ],
          "wednesday": [
            {
              "extra_fields": {},
              "index": 0,
              "weekday_name": "wednesday",
              "start_time": 330,
              "end_time": 360
            },
            {
              "extra_fields": {},
              "index": 1,
              "weekday_name": "wednesday",
              "start_time": 1050,
              "end_time": 1090
            }
          ],
          "thursday": [
            {
              "extra_fields": {},
              "index": 0,
              "weekday_name": "thursday",
              "start_time": 330,
              "end_time": 360
            },
            {
              "extra_fields": {},
              "index": 1,
              "weekday_name": "thursday",
              "start_time": 1050,
              "end_time": 1090
            }
          ],
          "friday": [
            {
              "extra_fields": {},
              "index": 0,
              "weekday_name": "friday",
              "start_time": 330,
              "end_time": 360
            },
            {
              "extra_fields": {},
              "index": 1,
              "weekday_name": "friday",
              "start_time": 1050,
              "end_time": 1090
            }
          ],
          "saturday": [
            {
              "extra_fields": {},
              "index": 0,
              "weekday_name": "saturday",
              "start_time": 330,
              "end_time": 360
            },
            {
              "extra_fields": {},
              "index": 1,
              "weekday_name": "saturday",
              "start_time": 1050,
              "end_time": 1090
            }
          ],
          "sunday": [
            {
              "extra_fields": {},
              "index": 0,
              "weekday_name": "sunday",
              "start_time": 330,
              "end_time": 360
            },
            {
              "extra_fields": {},
              "index": 1,
              "weekday_name": "sunday",
              "start_time": 1050,
              "end_time": 1090
            }
          ],
          "meta_info": {
            "min_slots_per_day": 0,
            "max_slots_per_day": 3,
            "setpoint_required_per_slot": false
          }
        },
        "time_program_circulation_pump": {
          "extra_fields": {},
          "monday": [],
          "tuesday": [],
          "wednesday": [],
          "thursday": [],
          "friday": [],
          "saturday": [],
          "sunday": [],
          "meta_info": {
            "min_slots_per_day": 0,
            "max_slots_per_day": 3,
            "setpoint_required_per_slot": false
          }
        },
        "current_dhw_temperature": 50.0,
        "tapping_setpoint": 55.0
      }
    ],
    "ventilation": [],
    "devices": [],
    "mpc": {
      "devices": []
    },
    "rts": {
      "statistics": []
    }
  }
]

```
```

**Comment by thomasgermain** [comment]
I didn't see there was some beta. Working correctly with https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.4b9 :+1:
