### ISSUE TITLE
Unable to import component: cannot import name 'DeviceInfo'

### ISSUE THREAD

**Issue by daviddepedroviejo** [signalkraft/mypyllant-component#145]
### Before submitting a new issue

- [X ] I redownloaded the latest release and restarted Home Assistant
- [X ] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [ X] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

After few months I've updated the integration and now is giving me an error when starting home assitant, the integration doesnt work anymore.

### Logs

`Este error se originó a partir de una integración personalizada.

Logger: homeassistant.setup
Source: custom_components/mypyllant/utils.py:12
Integration: myVAILLANT (documentation, issues)
First occurred: 14:20:49 (1 occurrences)
Last logged: 14:20:49

Setup failed for custom integration mypyllant: Unable to import component: cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/mypyllant/__init__.py", line 36, in <module>
    from .coordinator import SystemCoordinator, DailyDataCoordinator
  File "/config/custom_components/mypyllant/coordinator.py", line 27, in <module>
    from custom_components.mypyllant.utils import is_quota_exceeded_exception
  File "/config/custom_components/mypyllant/utils.py", line 12, in <module>
    from homeassistant.helpers.device_registry import DeviceInfo
ImportError: cannot import name 'DeviceInfo' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)

**Comment by signalkraft** [comment]
I guess you are on an older version of Home Assistant? Anything after 23.10 should not show this error.

**Comment by daviddepedroviejo** [comment]
You were right. It was an issue related to being in an old version. Closing the issue based on your comment. 

Thanks!
