### ISSUE TITLE
Error adding entities for domain climate with platform mypyllant

### ISSUE THREAD

**Issue by fhbonte** [signalkraft/mypyllant-component#146]
### Before submitting a new issue

- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

1) Error adding entities for domain climate with platform mypyllant
2) Error while setting up mypyllant platform for climate

### Logs
1)
```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:509
Integration: Klimaat (documentation, issues)
First occurred: 18:23:51 (1 occurrences)
Last logged: 18:23:51

Error adding entities for domain climate with platform mypyllant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 664, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 276, in capability_attributes
    supported_features = self.supported_features
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/climate.py", line 487, in supported_features
    | ClimateEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_OFF

```
2)
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:369
Integration: Klimaat (documentation, issues)
First occurred: 18:23:52 (1 occurrences)
Last logged: 18:23:52

Error while setting up mypyllant platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 369, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 664, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 276, in capability_attributes
    supported_features = self.supported_features
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/climate.py", line 487, in supported_features
    | ClimateEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_OFF

**Comment by signalkraft** [comment]
You need at least [Home Assistant 2024.2](https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded/)

**Comment by fhbonte** [comment]
Yes indeed, the issue is solved by upgrading HA Core.
Many thanks for your help and for creating this custom-component !
