### ISSUE TITLE
Climate entity gone

### ISSUE THREAD

**Issue by minosrex** [signalkraft/mypyllant-component#148]
### Before submitting a new issue

- [X] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [X] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [X] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Since the latest version of the component, new sensors have been added but the climate entity is no longer there.

### Logs

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:509
Integration: Klimaat (documentation, issues)
First occurred: 21:29:43 (1 occurrences)
Last logged: 21:29:43

Error adding entities for domain climate with platform mypyllant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 664, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 276, in capability_attributes
    supported_features = self.supported_features
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/climate.py", line 463, in supported_features
    | ClimateEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_OFF

Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:369
Integration: Klimaat ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 21:29:43 (1 occurrences)
Last logged: 21:29:43

Error while setting up mypyllant platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 369, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 664, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 276, in capability_attributes
    supported_features = self.supported_features
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/climate.py", line 463, in supported_features
    | ClimateEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_OFF

**Comment by StoniHome** [comment]
I've a similar issue, after update to v0.8.2 the following entities are gone

- Current Power
- ON/OFF Cycles
- Operation Time

**Comment by Tibinobo** [comment]
Ich habe auch ein ähnliches Problem. Ich bin zurück zu Version v0.7.4, bei allen nachfolgenden Versionen sind
- EIN/AUS-Zyklen
- Betriebszeit
verschwunden.

**Comment by signalkraft** [comment]
Please [read the note in the releases](https://github.com/signalkraft/mypyllant-component/releases/tag/v0.8.2).

**Comment by signalkraft** [comment]
As for the issue with `TURN_OFF`, you need at least Home Assistant 2024.2

**Comment by Tibinobo** [comment]
oh, Entschuldigung, das hatte ich noch nicht gelesen. Jetzt funktionieren diese Entitäten.Vielen Dank für die Mühe.Mit freundlichen Grüßen und frohe Ostern.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: signalkraft ***@***.***> Datum: 28.03.24  18:04  (GMT+01:00) An: signalkraft/mypyllant-component ***@***.***> Cc: Tibinobo ***@***.***>, Comment ***@***.***> Betreff: Re: [signalkraft/mypyllant-component] Climate entity gone (Issue #148) 
Please read the note in the releases.
