### ISSUE TITLE
aiohttp.http_exceptions.BadStatusLine: 400

### ISSUE THREAD

**Issue by svn2208** [signalkraft/mypyllant-component#155]
I installed my VR921 and got this result in the HA logs :( 
Some Ideas?  I can't see any entities, but run the authentication successfully. 

2024-04-15 15:27:34.115 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x01\x14\x01'
      ^

**Comment by signalkraft** [comment]
Did you enable debug logs? Can you post the whole thing? Just from this snippet, I can't tell what's going on.
