### ISSUE TITLE
Handling of more than one Heating Setups

### ISSUE THREAD

**Issue by Brudertac** [signalkraft/mypyllant-component#156]
### Before submitting a new issue

- [ X ] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [ X ] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [ X ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

Hello,

currently we have a myVaillant Account with more than one Heating Setups. (Means more than one sensoNET VR 921)

The Problem is that when i restart the mypyllant Integration (or HAOS itself) and one of those sensoNET VR 921 is Offline, i see an Error 404 in the Logs and none off my Heating Setups are shown in HA. (They are all Offline with no Data. But in Real Life only One is Offline...)

I hope you understand what i mean. :-)
Is there a way to change the Handling that this Error will be handled in another way?

Thanks and best regards.

**Comment by signalkraft** [comment]
Could you post debug logs, please? In theory, this integration should work with two controllers.

**Comment by Brudertac** [comment]
Off course, is that enough Data or should i leave Debugging on for  longer Time?

[home-assistant_mypyllant_2024-05-02T06-39-05.397Z.log](https://github.com/signalkraft/mypyllant-component/files/15184832/home-assistant_mypyllant_2024-05-02T06-39-05.397Z.log)

Thanks and best regards

**Comment by Brudertac** [comment]
Today i tried to restart the myVaillant Integration. This Error came up:

```
Unexpected error fetching myVAILLANT data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/coordinator.py", line 169, in _async_update_data
    data = [
           ^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 335, in get_systems
    control_identifier = await self.get_control_identifier(home.system_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 1068, in get_control_identifier
    return ControlIdentifier(control_identifier)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 744, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/enum.py", line 1158, in __new__
    raise ve_exc
ValueError: 'none' is not a valid ControlIdentifier
```

**Comment by signalkraft** [comment]
How does it look in the latest version? If the error persists, you would need to try [reverse engineering](https://signalkraft.com/mypyllant-component/3-reverse-engineering/) to find out what API endpoints your setup uses.

**Comment by boelle** [comment]
@Brudertac is this still an issue?

**Comment by Brudertac** [comment]
No, Problem is solved. (I think on API Side)
