### ISSUE TITLE
Unavailable entities - circuit_0_cooling_allowed, circuit_0_quick_veto_duration

### ISSUE THREAD

**Issue by herky999** [signalkraft/mypyllant-component#163]
### Before submitting a new issue

- [X] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [X] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [X] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Hello,
I don't see these entities in Home Assistant, they are unavailable:

binary_sensor.dom_circuit_0_cooling_allowed
number.dom_zone_obyvacka_circuit_0_quick_veto_duration

Vaillant aroTHERM plus + uniTOWER + VR 940f + sensoCOMFORT 720

Firmware: 0404.01.18

**Integration config:**
- Temperature controls overwrite time program instead of setting quick veto - **on/off without difference**
- Fetch real-time statistics (not supported on every system) - **on**
- Fetch real-time power usage (not supported on every system) - **on**

If necessary, I will send the complete logfile

Thank you

### Logs

```
2024-05-06 12:07:13.489 DEBUG (MainThread) [custom_components.mypyllant.sensor] Creating efficiency sensor for System xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
2024-05-06 12:07:13.489 DEBUG (MainThread) [custom_components.mypyllant.sensor] Creating efficiency sensor for System xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx and Device 0
2024-05-06 12:07:13.489 DEBUG (MainThread) [custom_components.mypyllant.sensor] Finishing init of Dom Device 0 aroTHERM plus Consumed Electrical Energy Domestic Hot Water = 0.0 and unique id mypyllant_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_0
2024-05-06 12:07:13.489 DEBUG (MainThread) [custom_components.mypyllant.sensor] Finishing init of Dom Device 0 aroTHERM plus Consumed Electrical Energy Heating = 62.97828125 and unique id mypyllant_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_1
2024-05-06 12:07:13.489 DEBUG (MainThread) [custom_components.mypyllant.sensor] Finishing init of Dom Device 0 aroTHERM plus Earned Environment Energy Domestic Hot Water = 0.0 and unique id mypyllant_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_2
2024-05-06 12:07:13.490 DEBUG (MainThread) [custom_components.mypyllant.sensor] Finishing init of Dom Device 0 aroTHERM plus Earned Environment Energy Heating = 0.0 and unique id mypyllant_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_3
2024-05-06 12:07:13.490 DEBUG (MainThread) [custom_components.mypyllant.sensor] Finishing init of Dom Device 0 aroTHERM plus Heat Generated Domestic Hot Water = 0.0 and unique id mypyllant_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_4
2024-05-06 12:07:13.490 DEBUG (MainThread) [custom_components.mypyllant.sensor] Finishing init of Dom Device 0 aroTHERM plus Heat Generated Heating = 0.0 and unique id mypyllant_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_5
2024-05-06 12:07:13.490 DEBUG (MainThread) [custom_components.mypyllant.sensor] Creating efficiency sensor for System xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx and Device 1
2024-05-06 12:07:13.490 DEBUG (MainThread) [custom_components.mypyllant.sensor] Finishing init of Dom Device 1 uniTOWER Consumed Electrical Energy Heating = 26.632216309136435 and unique id mypyllant_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_0
2024-05-06 12:07:13.490 DEBUG (MainThread) [custom_components.mypyllant.sensor] Finishing init of Dom Device 1 uniTOWER Heat Generated Heating = 26.63212300115375 and unique id mypyllant_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx_1
2024-05-06 12:07:13.490 DEBUG (MainThread) [custom_components.mypyllant.water_heater] Setting up water heater entity services for <EntityPlatform domain=water_heater platform_name=mypyllant config_entry=<homeassistant.config_entries.ConfigEntry object at 0x7f00daad5140>>
2024-05-06 12:07:13.545 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform mypyllant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 315, in capability_attributes
    supported_features = self.supported_features_compat
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 670, in supported_features_compat
    features = self.supported_features
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/climate.py", line 515, in supported_features
    | ClimateEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_OFF
2024-05-06 12:07:13.552 ERROR (MainThread) [homeassistant.components.climate] Error while setting up mypyllant platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 315, in capability_attributes
    supported_features = self.supported_features_compat
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 670, in supported_features_compat
    features = self.supported_features
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/climate.py", line 515, in supported_features
    | ClimateEntityFeature.TURN_OFF
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: TURN_OFF
2024-05-06 12:08:13.440 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Starting async update data for SystemCoordinator
2024-05-06 12:08:13.441 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Waiting 37s until token refresh for xxxxxxxxx@xxxxxxxxx
2024-05-06 12:08:14.358 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Finished fetching myVAILLANT data in 0.917 seconds (success: True)
```

**Comment by herky999** [comment]
updating the home assistant helped

**Comment by herky999** [comment]
.
