### ISSUE TITLE
"Detected blocking call" warning after update to HA Core 2024.6.2 

### ISSUE THREAD

**Issue by mzaufl** [signalkraft/mypyllant-component#172]
### Before submitting a new issue

- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Pleased to post by warning

New Warning in SystemLog after update to HA Core 2024.6.2. No other issue.

### Logs

```
Logger: homeassistant.util.loop
Quelle: util/loop.py:84
Erstmals aufgetreten: 11. Juni 2024 um 19:08:05 (1 Vorkommnisse)
Zuletzt protokolliert: 11. Juni 2024 um 19:08:05

Detected blocking call to open inside the event loop by custom integration 'mypyllant' at custom_components/mypyllant/coordinator.py, line 169: data = [ (offender: /usr/local/lib/python3.12/site-packages/dateutil/tz/tz.py, line 464: fileobj = open(fileobj, 'rb')), please create a bug report at https://github.com/signalkraft/mypyllant-component/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/mypyllant/__init__.py", line 122, in async_setup_entry await system_coordinator.async_refresh() File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 288, in async_refresh await self._async_refresh(log_failures=True) File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 312, in _async_refresh self.data = await self._async_update_data() File "/config/custom_components/mypyllant/coordinator.py", line 169, in _async_update_data data = [
```

**Comment by Honzik1234** [comment]
Same error
[home-assistant_mypyllant_2024-06-18T06-02-37.490Z.log](https://github.com/user-attachments/files/15881157/home-assistant_mypyllant_2024-06-18T06-02-37.490Z.log)

https://github.com/signalkraft/mypyllant-component/assets/112153443/83594af1-1679-478e-b2d4-566e3852c596

**Comment by signalkraft** [comment]
Should work in the latest release https://github.com/signalkraft/mypyllant-component/releases/tag/v0.8.4
