### ISSUE TITLE
Request support for VC 20CS ecoTEC

### ISSUE THREAD

**Issue by techsuhi** [signalkraft/mypyllant-component#19]
Hi there,

I'm looking for energy vaules for my Vaillant VC 20CS/1-7 (N-DE) ecoTEC exclusive + sensoCOMFORT VRC 720 + sensoNET VR 921 which sensors are not created at the moment. But in the DEBUG log i can see the vaules:

```
....
2023-06-19 23:00:49.104 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='GET', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/emf/v2/21194300202609650XXXXXXXX/devices/67052dda-be47-52d1-b8ee-XXXXXXXXXX/buckets'), headers=<CIMultiDict('Authorization': 'Bearer xxxx', 'x-app-identifier': 'VAILLANT', 'Accept-Language': 'en-GB', 'Accept': 'application/json, text/plain, */*', 'x-client-locale': 'en-GB', 'x-idm-identifier': 'KEYCLOAK', 'ocp-apim-subscription-key': '1e0a2f3511fb4c5bbb1cxxxxxxxxx', 'User-Agent': 'okhttp/4.9.2', 'Connection': 'keep-alive')>)
2023-06-19 23:00:49.180 DEBUG (MainThread) [myPyllant.api] Got response {"startDate":"2023-06-19T00:00:00Z","endDate":"2023-06-20T00:00:00Z","resolution":"DAY","operationMode":"DOMESTIC_HOT_WATER","energyType":"CONSUMED_ELECTRICAL_ENERGY","totalConsumption":91.5625,"data":[{"startDate":"2023-06-19T00:00:00Z","endDate":"2023-06-20T00:00:00Z","value":91.5625}]}

2023-06-19 23:00:49.181 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='GET', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/emf/v2/21194300202609650XXXXXXXX/devices/67052dda-be47-52d1-b8ee-XXXXXXXXXX/buckets'), headers=<CIMultiDict('Authorization': 'Bearer xxxx', 'x-app-identifier': 'VAILLANT', 'Accept-Language': 'en-GB', 'Accept': 'application/json, text/plain, */*', 'x-client-locale': 'en-GB', 'x-idm-identifier': 'KEYCLOAK', 'ocp-apim-subscription-key': '1e0a2f3511fb4c5bbb1cxxxxxxxxx', 'User-Agent': 'okhttp/4.9.2', 'Connection': 'keep-alive')>)
2023-06-19 23:00:49.245 DEBUG (MainThread) [myPyllant.api] Got response {"startDate":"2023-06-19T00:00:00Z","endDate":"2023-06-20T00:00:00Z","resolution":"DAY","operationMode":"HEATING","energyType":"CONSUMED_ELECTRICAL_ENERGY","totalConsumption":43.293575,"data":[{"startDate":"2023-06-19T00:00:00Z","endDate":"2023-06-20T00:00:00Z","value":43.293575}]}

2023-06-19 23:00:49.245 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='GET', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/emf/v2/21194300202609650XXXXXXXX/devices/67052dda-be47-52d1-b8ee-XXXXXXXXXX/buckets'), headers=<CIMultiDict('Authorization': 'Bearer xxxx', 'x-app-identifier': 'VAILLANT', 'Accept-Language': 'en-GB', 'Accept': 'application/json, text/plain, */*', 'x-client-locale': 'en-GB', 'x-idm-identifier': 'KEYCLOAK', 'ocp-apim-subscription-key': '1e0a2f3511fb4c5bbb1cxxxxxxxxx', 'User-Agent': 'okhttp/4.9.2', 'Connection': 'keep-alive')>)
2023-06-19 23:00:49.293 DEBUG (MainThread) [myPyllant.api] Got response {"startDate":"2023-06-19T00:00:00Z","endDate":"2023-06-20T00:00:00Z","resolution":"DAY","operationMode":"DOMESTIC_HOT_WATER","energyType":"CONSUMED_PRIMARY_ENERGY","totalConsumption":6373.0,"data":[{"startDate":"2023-06-19T00:00:00Z","endDate":"2023-06-20T00:00:00Z","value":6373.0}]}

2023-06-19 23:00:49.294 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='GET', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/emf/v2/21194300202609650XXXXXXXX/devices/67052dda-be47-52d1-b8ee-XXXXXXXXXX/buckets'), headers=<CIMultiDict('Authorization': 'Bearer xxxx', 'x-app-identifier': 'VAILLANT', 'Accept-Language': 'en-GB', 'Accept': 'application/json, text/plain, */*', 'x-client-locale': 'en-GB', 'x-idm-identifier': 'KEYCLOAK', 'ocp-apim-subscription-key': '1e0a2f3511fb4c5bbb1cxxxxxxxxx', 'User-Agent': 'okhttp/4.9.2', 'Connection': 'keep-alive')>)
2023-06-19 23:00:49.351 DEBUG (MainThread) [myPyllant.api] Got response {"startDate":"2023-06-19T00:00:00Z","endDate":"2023-06-20T00:00:00Z","resolution":"DAY","operationMode":"HEATING","energyType":"CONSUMED_PRIMARY_ENERGY","totalConsumption":0.0,"data":[{"startDate":"2023-06-19T00:00:00Z","endDate":"2023-06-20T00:00:00Z","value":0.0}]}

2023-06-19 23:00:49.351 DEBUG (MainThread) [custom_components.mypyllant] Finished fetching myVAILLANT data in 0.391 seconds (success: True)
...

2023-06-19 23:13:53.960 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='GET', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/emf/v2/2119430020260965xxxxxxxxx/devices/67052dda-be47-52d1-b8ee-xxxxxxxx/buckets'), headers=<CIMultiDict('Authorization': 'Bearer xxxxxxx', 'x-app-identifier': 'VAILLANT', 'Accept-Language': 'en-GB', 'Accept': 'application/json, text/plain, */*', 'x-client-locale': 'en-GB', 'x-idm-identifier': 'KEYCLOAK', 'ocp-apim-subscription-key': '1e0a2f3511fb4c5bbb1xxxxxxx', 'User-Agent': 'okhttp/4.9.2', 'Connection': 'keep-alive')>)
2023-06-19 23:13:54.015 DEBUG (MainThread) [myPyllant.api] Got response {"startDate":"2023-06-19T11:13:53Z","endDate":"2023-06-20T11:13:53Z","resolution":"HOUR","operationMode":"DOMESTIC_HOT_WATER","energyType":"CONSUMED_ELECTRICAL_ENERGY","totalConsumption":41.23437,"data":[{"startDate":"2023-06-19T11:00:00Z","endDate":"2023-06-19T12:00:00Z","value":0.0},{"startDate":"2023-06-19T12:00:00Z","endDate":"2023-06-19T13:00:00Z","value":0.0},{"startDate":"2023-06-19T13:00:00Z","endDate":"2023-06-19T14:00:00Z","value":21.5204},{"startDate":"2023-06-19T14:00:00Z","endDate":"2023-06-19T15:00:00Z","value":0.1202257},{"startDate":"2023-06-19T15:00:00Z","endDate":"2023-06-19T16:00:00Z","value":0.0},{"startDate":"2023-06-19T16:00:00Z","endDate":"2023-06-19T17:00:00Z","value":0.0},{"startDate":"2023-06-19T17:00:00Z","endDate":"2023-06-19T18:00:00Z","value":10.578554},{"startDate":"2023-06-19T18:00:00Z","endDate":"2023-06-19T19:00:00Z","value":8.962968},{"startDate":"2023-06-19T19:00:00Z","endDate":"2023-06-19T20:00:00Z","value":0.052226562},{"startDate":"2023-06-19T20:00:00Z","endDate":"2023-06-19T21:00:00Z","value":0.0},{"startDate":"2023-06-19T21:00:00Z","endDate":"2023-06-19T22:00:00Z","value":0.0},{"startDate":"2023-06-19T22:00:00Z","endDate":"2023-06-19T23:00:00Z"},{"startDate":"2023-06-19T23:00:00Z","endDate":"2023-06-20T00:00:00Z"},{"startDate":"2023-06-20T00:00:00Z","endDate":"2023-06-20T01:00:00Z"},{"startDate":"2023-06-20T01:00:00Z","endDate":"2023-06-20T02:00:00Z"},{"startDate":"2023-06-20T02:00:00Z","endDate":"2023-06-20T03:00:00Z"},{"startDate":"2023-06-20T03:00:00Z","endDate":"2023-06-20T04:00:00Z"},{"startDate":"2023-06-20T04:00:00Z","endDate":"2023-06-20T05:00:00Z"},{"startDate":"2023-06-20T05:00:00Z","endDate":"2023-06-20T06:00:00Z"},{"startDate":"2023-06-20T06:00:00Z","endDate":"2023-06-20T07:00:00Z"},{"startDate":"2023-06-20T07:00:00Z","endDate":"2023-06-20T08:00:00Z"},{"startDate":"2023-06-20T08:00:00Z","endDate":"2023-06-20T09:00:00Z"},{"startDate":"2023-06-20T09:00:00Z","endDate":"2023-06-20T10:00:00Z"},{"startDate":"2023-06-20T10:00:00Z","endDate":"2023-06-20T11:00:00Z"},{"startDate":"2023-06-20T11:00:00Z","endDate":"2023-06-20T12:00:00Z"}]}
2023-06-19 23:13:54.016 ERROR (MainThread) [custom_components.mypyllant] Unexpected error fetching myVAILLANT data: 14 validation errors for DeviceData
data -> 11 -> value
  field required (type=value_error.missing)
data -> 12 -> value
  field required (type=value_error.missing)
data -> 13 -> value
  field required (type=value_error.missing)
data -> 14 -> value
  field required (type=value_error.missing)
data -> 15 -> value
  field required (type=value_error.missing)
data -> 16 -> value
  field required (type=value_error.missing)
data -> 17 -> value
  field required (type=value_error.missing)
data -> 18 -> value
  field required (type=value_error.missing)
data -> 19 -> value
  field required (type=value_error.missing)
data -> 20 -> value
  field required (type=value_error.missing)
data -> 21 -> value
  field required (type=value_error.missing)
data -> 22 -> value
  field required (type=value_error.missing)
data -> 23 -> value
  field required (type=value_error.missing)
data -> 24 -> value
  field required (type=value_error.missing)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/mypyllant/__init__.py", line 165, in _async_update_data
    data.append([da async for da in device_data])
  File "/config/custom_components/mypyllant/__init__.py", line 165, in <listcomp>
    data.append([da async for da in device_data])
  File "/usr/local/lib/python3.10/site-packages/myPyllant/api.py", line 281, in get_data_by_device
    yield DeviceData(
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 259, in __init__
    super().__init__(device=device, **kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 14 validation errors for DeviceData
data -> 11 -> value
  field required (type=value_error.missing)
data -> 12 -> value
  field required (type=value_error.missing)
data -> 13 -> value
  field required (type=value_error.missing)
data -> 14 -> value
  field required (type=value_error.missing)
data -> 15 -> value
  field required (type=value_error.missing)
data -> 16 -> value
  field required (type=value_error.missing)
data -> 17 -> value
  field required (type=value_error.missing)
data -> 18 -> value
  field required (type=value_error.missing)
data -> 19 -> value
  field required (type=value_error.missing)
data -> 20 -> value
  field required (type=value_error.missing)
data -> 21 -> value
  field required (type=value_error.missing)
data -> 22 -> value
  field required (type=value_error.missing)
data -> 23 -> value
  field required (type=value_error.missing)
data -> 24 -> value
  field required (type=value_error.missing)
2023-06-19 23:13:54.017 DEBUG (MainThread) [custom_components.mypyllant] Finished fetching myVAILLANT data in 0.166 seconds (success: False)
2023-06-19 23:13:54.017 DEBUG (MainThread) [custom_components.mypyllant] Refreshing DailyDataCoordinator
```

Thanks in advance 👍

**Comment by signalkraft** [comment]
You may have better luck with the latest beta version v0.3.0b1. Let me know how it goes!
