### ISSUE TITLE
[myPyllant.api] Could not get rooms data

### ISSUE THREAD

**Issue by barto64** [signalkraft/mypyllant-component#196]
### Problem description
Not the end of the world, but after the latest update HA Log is throwing WARNING meesages every second making the log to growth exponentially.

### Logs
2024-07-22 17:46:51.642 WARNING (MainThread) [myPyllant.api] Could not get rooms data
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 1387, in get_ambisense_rooms
    response = await self.aiohttp_session.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 694, in _request
    await raise_for_status(resp)
  File "/usr/local/lib/python3.12/site-packages/myPyllant/http_client.py", line 73, in on_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 409, message='Conflict', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/api/v1/ambisense/facilities/f0861e7f-093c-41e3-a1f7-7fae0c790c58/rooms')

**Comment by LeiChat** [comment]
v.0.8.13 - Seeing the same errors for, line 1387, in get_ambisense_rooms.

**Comment by mzaufl** [comment]
v0.8.13 same Issue. Thx for fixing!

**Comment by signalkraft** [comment]
Please disable "Fetch Ambisense Room Thermostats" in the options of the integration, and let me know if it goes away please!

**Comment by LeiChat** [comment]
Yes, thank you.

**Comment by mzaufl** [comment]
Scheint zu funktionieren. Nach deaktivieren der u.a. Option auch nach
Neustart keine Fehler mehr, Danke


Seems to work. After deactivating the option among other things, no more
errors even after restarting, thank you


signalkraft ***@***.***> schrieb am Sa., 27. Juli 2024, 09:44:

**Comment by boelle** [comment]
@barto64 is the issue solved ?

**Comment by boelle** [comment]
@barto64 if so then maybe hit close below?

i'm just trying to help @signalkraft getting a shorter and "cleaner" list to work from

**Comment by damstra88** [comment]
i still have this issue... the option Fetch ambisense room data is off. Was already off, but to be sure i activated and deactivated. Still see this: 

2025-05-21 20:42:41.127 WARNING (MainThread) [myPyllant.api] Could not get rooms data
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/myPyllant/api.py", line 1400, in get_ambisense_rooms
    response = await self.aiohttp_session.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/myPyllant/http_client.py", line 30, in _request
    return await super()._request(method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 832, in _request
    await raise_for_status(resp)
  File "/usr/local/lib/python3.13/site-packages/myPyllant/http_client.py", line 83, in on_raise_for_status
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 1161, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
