### ISSUE TITLE
WARNING (MainThread) [myPyllant.api] Could not get energy management data

### ISSUE THREAD

**Issue by jan666** [signalkraft/mypyllant-component#198]
### Before submitting a new issue

- [X] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [X] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [ ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

My Arotherm Heat Pump was installed and I added the component to my home assistant. From the UI everything looks good, data is updated but my hass log is flooded with this (see log). Is this something that should not happen? Maybe somehow releated to my setup?

### Logs

```
2024-07-29 13:24:17.678 WARNING (MainThread) [myPyllant.api] Could not get energy management data
Traceback (most recent call last):
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/myPyllant/api.py", line 1310, in get_energy_management
    response = await self.aiohttp_session.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/aiohttp/client.py", line 694, in _request
    await raise_for_status(resp)
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/myPyllant/http_client.py", line 73, in on_raise_for_status
    response.raise_for_status()
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/eebus/energy-management/<...>')
2024-07-29 13:25:18.658 WARNING (MainThread) [myPyllant.api] Could not get energy management data
Traceback (most recent call last):
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/myPyllant/api.py", line 1310, in get_energy_management
    response = await self.aiohttp_session.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/aiohttp/client.py", line 694, in _request
    await raise_for_status(resp)
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/myPyllant/http_client.py", line 73, in on_raise_for_status
    response.raise_for_status()
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/eebus/energy-management/<...>')
2024-07-29 13:26:19.637 WARNING (MainThread) [myPyllant.api] Could not get energy management data
Traceback (most recent call last):
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/myPyllant/api.py", line 1310, in get_energy_management
    response = await self.aiohttp_session.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/aiohttp/client.py", line 694, in _request
    await raise_for_status(resp)
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/myPyllant/http_client.py", line 73, in on_raise_for_status
    response.raise_for_status()
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/eebus/energy-management/<...>')
2024-07-29 13:26:44.247 WARNING (MainThread) [myPyllant.api] Could not get energy management data
Traceback (most recent call last):
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/myPyllant/api.py", line 1310, in get_energy_management
    response = await self.aiohttp_session.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/aiohttp/client.py", line 694, in _request
    await raise_for_status(resp)
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/myPyllant/http_client.py", line 73, in on_raise_for_status
    response.raise_for_status()
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/eebus/energy-management/<...>')
2024-07-29 13:40:38.394 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 255, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 411, in _async_refresh
    self.async_update_listeners()
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 165, in async_update_listeners
    update_callback()
  File "/home/homeassistant/.homeassistant/custom_components/mypyllant/sensor.py", line 889, in _handle_coordinator_update
    super()._handle_coordinator_update()
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 491, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1133, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1068, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/home/homeassistant/ha-py312/lib/python3.12/site-packages/homeassistant/components/sensor/__init__.py", line 533, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/home/homeassistant/.homeassistant/custom_components/mypyllant/sensor.py", line 885, in native_value
    return self.device_data.total_consumption_rounded
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'total_consumption_rounded'

```

**Comment by xxLeoxx93** [comment]
Same issue - did you find a solution?

**Comment by ghj74** [comment]
Same issue here. Any solutions?

**Comment by jan666** [comment]
> [@jan666](https://github.com/jan666) still a problem?

I'm using ebusd now, I don't know if the issue is still there.

**Comment by boelle** [comment]
we might let @signalkraft chime in

**Comment by boelle** [comment]
@signalkraft poke
