### ISSUE TITLE
Ventilation boost control does not work

### ISSUE THREAD

**Issue by hendrikwolf79** [signalkraft/mypyllant-component#220]
### Before submitting a new issue

- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

When you press the ventilation boost switch, a message appears saying that the VRC700 controller does not support this. When switching via the Vaillant app or on the heater, the status is displayed correctly in the integration.
Same result if the function is to be run as a service.

### Logs

```
Logger: homeassistant.components.websocket_api.http.connection
Quelle: components/websocket_api/commands.py:245
Integration: Home Assistant WebSocket API (Dokumentation, Probleme)
Erstmals aufgetreten: 07:41:52 (1 Vorkommnisse)
Zuletzt protokolliert: 07:41:52

[546896040656] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/mypyllant/switch.py", line 174, in async_turn_off
    await self.coordinator.api.cancel_ventilation_boost(self.system)
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 958, in cancel_ventilation_boost
    raise ValueError("Not supported on VRC700 controllers")
ValueError: Not supported on VRC700 controllers

```

**Comment by Peaters** [comment]
Helo, same problem here. Ventilation boost never worked in my HA. 
My setup is VWL 75/5 IS + recoVAIR 260/4 + VRC700, communication via VR920

LOG:
```
Logger: homeassistant.components.websocket_api.http.connection
Zdroj: components/websocket_api/commands.py:245
integrace: Home Assistant WebSocket API (dokumentace, problémy)
První výskyt: 14:46:22 (1 výskyty)
Naposledy logováno: 14:46:22

[547438468048] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2804, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 996, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1068, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/mypyllant/switch.py", line 170, in async_turn_on
    await self.coordinator.api.set_ventilation_boost(self.system)
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 944, in set_ventilation_boost
    raise ValueError("Not supported on VRC700 controllers")
ValueError: Not supported on VRC700 controllers
```

**Comment by lennartjung** [comment]
I have the same issue, similiar setup like @Peaters, only VWL 125/5 S2 +  recoVAIR 360/4 are different. Would be great if this could be solved as it gives ability to start the ventilation boost when the bathrooms humidity is too high

**Comment by boelle** [comment]
@signalkraft also one you might look at

**Comment by boelle** [comment]
@signalkraft poke
