### ISSUE TITLE
Not starting because of missing enum value CYLINDER_BOOST

### ISSUE THREAD

**Issue by tritter** [signalkraft/mypyllant-component#23]
Currently no devices have been added because of this exception:

```2023-08-25 21:17:09.996 ERROR (MainThread) [custom_components.mypyllant] Unexpected error fetching myVAILLANT data: 1 validation error for DomesticHotWater
current_special_function
value is not a valid enumeration member; permitted: 'CYLINDER_BOOST', 'REGULAR' (type=type_error.enum; enum_values=[<DHWCurrentSpecialFunction.CYLINDER_BOOST: 'CYLINDER_BOOST'>, <DHWCurrentSpecialFunction.REGULAR: 'REGULAR'>])
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/mypyllant/__init__.py", line 155, in _async_update_data
async for system in await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 281, in get_systems
system = System(
^^^^^^^
File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 167, in __init__
self.domestic_hot_water = [
^
File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 168, in <listcomp>
DomesticHotWater(system_id=self.id, **d) for d in self._merge_object("dhw")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 341, in __init__
raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for DomesticHotWater
current_special_function

**Comment by signalkraft** [comment]
It should say somewhere what the unexpected value was, could you try and find that? In your error message it only shows what values it expects.

**Comment by tritter** [comment]
@signalkraft sorry for the delay, I think the following are missing:
``` pydantic_core._pydantic_core.ValidationError: 3 validation errors for Zone
desired_room_temperature_setpoint_cooling
  Field required [type=missing, input_value={'system_id': '8545c5f0-f...iated_circuit_index': 0}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
quick_veto_start_date_time
  Field required [type=missing, input_value={'system_id': '8545c5f0-f...iated_circuit_index': 0}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
quick_veto_end_date_time
  Field required [type=missing, input_value={'system_id': '8545c5f0-f...iated_circuit_index': 0}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.3/v/missing
```

**Comment by signalkraft** [comment]
Cooling should work. Could you turn on debug logging and post the whole thing, or [post test data ](https://signalkraft.com/mypyllant-component/3-contributing/#contributing-test-data)

**Comment by tritter** [comment]
@signalkraft yes, attached the test data. And a debug log! 
[pyallant.log](https://github.com/signalkraft/mypyllant-component/files/12697827/pyallant.log)
[4d9f32ea56ab6fc138e396e07c65e6424b245015.zip](https://github.com/signalkraft/mypyllant-component/files/12697829/4d9f32ea56ab6fc138e396e07c65e6424b245015.zip)

**Comment by signalkraft** [comment]
Main issues seems to be, that you're running a newer version of `pydantic` that I've not upgraded to, yet. Try going to the last 1.x version.

The original error with `current_special_function` shouldn't happen with the debug log you posted, there's only supported values in there.
