### ISSUE TITLE
No Data since 3 or 4 Version Updates

### ISSUE THREAD

**Issue by Brudertac** [signalkraft/mypyllant-component#230]
### Before submitting a new issue

- [ x ] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [ x ] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [ x ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

There are no Data anymore from the Plugin. 

### Logs

`2024-10-31 08:50:46.566 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args (PosixPath('/usr/local/lib/python3.12/site-packages/mypyllant-0.8.32.dist-info/METADATA'),) inside the event loop by custom integration 'mypyllant' at custom_components/mypyllant/__init__.py, line 90: version("myPyllant"), (offender: /usr/local/lib/python3.12/pathlib.py, line 1027: with self.open(mode='r', encoding=encoding, errors=errors) as f:), please create a bug report at https://github.com/signalkraft/mypyllant-component/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 120, in post
    await hass.config_entries.async_reload(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2010, in async_reload
    return await self.async_setup(entry_id, _lock=False)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1934, in async_setup
    await entry.async_setup(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/mypyllant/__init__.py", line 90, in async_setup_entry
    version("myPyllant"),

2024-10-31 08:50:46.651 DEBUG (MainThread) [custom_components.mypyllant] Starting mypyllant component v0.8.18 (library 0.8.32) with homeassistant 2024.10.4, pydantic 1.10.17, and aiohttp 3.10.8
2024-10-31 08:50:46.652 DEBUG (MainThread) [custom_components.mypyllant] Creating API and logging in with EMAIL in realm germany
2024-10-31 08:50:47.884 DEBUG (MainThread) [custom_components.mypyllant] Refreshing SystemCoordinator
2024-10-31 08:50:47.884 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Starting async update data for SystemCoordinator
2024-10-31 08:50:47.884 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Waiting 119s until token refresh for EMAIL
2024-10-31 08:50:50.913 ERROR (MainThread) [custom_components.mypyllant.coordinator] Unexpected error fetching myVAILLANT data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/coordinator.py", line 177, in _async_update_data
    data = [
           ^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 359, in get_systems
    system = System.from_api(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 945, in from_api
    Circuit.from_api(system_id=system.id, timezone=system.timezone, **c)
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 83, in from_api
    return cls(**data)
           ^^^^^^^^^^^
  File "pydantic/dataclasses.py", line 329, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
  File "pydantic/dataclasses.py", line 293, in pydantic.dataclasses._add_pydantic_validation_attributes.handle_extra_init
TypeError: Circuit.__init__() missing 1 required positional argument: 'circuit_state'
2024-10-31 08:50:50.916 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Finished fetching myVAILLANT data in 3.031 seconds (success: False)
2024-10-31 08:50:50.916 DEBUG (MainThread) [custom_components.mypyllant] Refreshing DailyDataCoordinator
2024-10-31 08:50:50.916 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Starting async update data for DailyDataCoordinator
2024-10-31 08:50:50.916 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Waiting 116s until token refresh for EMAIL
2024-10-31 08:50:51.291 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Getting daily data for 0b94cc69-1585-49a8-8ae5-86ea2e740b44 from 2024-10-31 00:00:00+01:00 to 2024-11-01 00:00:00+01:00
2024-10-31 08:50:51.292 DEBUG (MainThread) [custom_components.mypyllant.coordinator] No devices in 0b94cc69-1585-49a8-8ae5-86ea2e740b44
2024-10-31 08:50:51.586 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Getting daily data for 0b3c8927-fa60-4673-be51-d3e5c85e8232 from 2024-10-31 00:00:00+01:00 to 2024-11-01 00:00:00+01:00
2024-10-31 08:50:51.586 DEBUG (MainThread) [custom_components.mypyllant.coordinator] No devices in 0b3c8927-fa60-4673-be51-d3e5c85e8232
2024-10-31 08:50:51.932 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Getting daily data for f7d80f51-6171-4d56-9ec7-187c4bd93e83 from 2024-10-31 00:00:00+01:00 to 2024-11-01 00:00:00+01:00
2024-10-31 08:50:51.932 DEBUG (MainThread) [custom_components.mypyllant.coordinator] No devices in f7d80f51-6171-4d56-9ec7-187c4bd93e83
2024-10-31 08:50:52.258 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Getting daily data for e73fa8d7-a7cc-4a2d-9397-af425c22c8b3 from 2024-10-31 00:00:00+01:00 to 2024-11-01 00:00:00+01:00
2024-10-31 08:50:53.452 ERROR (MainThread) [custom_components.mypyllant.coordinator] Unexpected error fetching myVAILLANT data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/coordinator.py", line 213, in _async_update_data
    async for system in await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 359, in get_systems
    system = System.from_api(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 945, in from_api
    Circuit.from_api(system_id=system.id, timezone=system.timezone, **c)
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 83, in from_api
    return cls(**data)
           ^^^^^^^^^^^
  File "pydantic/dataclasses.py", line 329, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
  File "pydantic/dataclasses.py", line 293, in pydantic.dataclasses._add_pydantic_validation_attributes.handle_extra_init
TypeError: Circuit.__init__() missing 1 required positional argument: 'circuit_state'
2024-10-31 08:50:53.454 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Finished fetching myVAILLANT data in 2.538 seconds (success: False)
2024-10-31 08:50:53.455 WARNING (MainThread) [custom_components.mypyllant.binary_sensor] No system data, skipping binary sensors
2024-10-31 08:50:53.456 WARNING (MainThread) [custom_components.mypyllant.calendar] No system data, skipping calendar entities
2024-10-31 08:50:53.457 WARNING (MainThread) [custom_components.mypyllant.climate] No system data, skipping climate
2024-10-31 08:50:53.458 WARNING (MainThread) [custom_components.mypyllant.datetime] No system data, skipping date time entities
2024-10-31 08:50:53.459 WARNING (MainThread) [custom_components.mypyllant.number] No system data, skipping number entities
2024-10-31 08:50:53.460 WARNING (MainThread) [custom_components.mypyllant.sensor] No system data, skipping sensors
2024-10-31 08:50:53.461 DEBUG (MainThread) [custom_components.mypyllant.sensor] Daily data: None
2024-10-31 08:50:53.461 WARNING (MainThread) [custom_components.mypyllant.sensor] No daily data, skipping sensors
2024-10-31 08:50:53.462 WARNING (MainThread) [custom_components.mypyllant.switch] No system data, skipping switch entities
2024-10-31 08:50:53.463 WARNING (MainThread) [custom_components.mypyllant.water_heater] No system data, skipping water heater
`

**Comment by signalkraft** [comment]
This might be addressed in the latest release, let me know if that works for you!

**Comment by Brudertac** [comment]
Holymoly, it works again. Many Thanks!! 👍
