### ISSUE TITLE
ON/OFF/AUTO Switching of Heater not working

### ISSUE THREAD

**Issue by rbunknown** [signalkraft/mypyllant-component#24]
Hello

all functions for my heater work except  climate.zone_0_hvac_modes: off, heat_cool, auto

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/mypyllant/climate.py:280
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 08:44:51 (13 occurrences)
Last logged: 14:35:39

[547183080256] 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/zones/0/heatingOperationMode')
[547379693888] 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/zones/0/heatingOperationMode')
[546800498112] 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/zones/0/heatingOperationMode')
[546775130304] 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/zones/0/heatingOperationMode')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/mypyllant/climate.py", line 280, in async_set_hvac_mode
    await self.coordinator.api.set_zone_heating_operating_mode(
  File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 341, in set_zone_heating_operating_mode
    return await self.aiohttp_session.post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/zones/0/heatingOperationMode')

**Comment by signalkraft** [comment]
Should be fixed in the latest beta release, let me know if it works please!

**Comment by rbunknown** [comment]
Hello Signalkraft,

with beta v0.5.0b1 all functions work again, include switch on/off/auto on a vaillant Vaillant ECOTEC PLUS VCW20/1 boiler + sensoCOMFORT VRC 720 + sensoNET VR 921 , so you can put this combination on the compatibility list.
Thank you again for the fast fix and response!
René

**Comment by rbunknown** [comment]
Hello Signalkraft,

with beta v0.5.0b1 all functions work again, include switch on/off/auto on
a Vaillant ECOTEC PLUS VCW20/1 boiler + sensoCOMFORT VRC 720 + sensoNET VR
921 , so you can put this combination on the compatibility list too.
Thank you again for the fast fix and response! I use this component daily
and use it in some automations, so this component you build is very
helpfull on the germany gas prices...


René

Am Do., 31. Aug. 2023 um 23:46 Uhr schrieb signalkraft <
***@***.***>:
