### ISSUE TITLE
Die Aktion water_heater/set_operation_mode konnte nicht ausgeführt werden. 'NoneType' object has no attribute 'general'

### ISSUE THREAD

**Issue by easyhoo** [signalkraft/mypyllant-component#244]
### Before submitting a new issue

- [ ] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [ ] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [ ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Beim Versuch die Vaillant Geräte zu schalten kommt seit dem jüngsten HA Upgrade diese NoneType Meldung.
Die Aktion water_heater/set_operation_mode konnte nicht ausgeführt werden. 'NoneType' object has no attribute 'general'

### Logs

```
AttributeError: 'NoneType' object has no attribute 'general'
2024-12-03 12:42:14.147 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140594993658848] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 359, in async_handle_set_operation_mode
    await self.async_set_operation_mode(operation_mode)
  File "/config/custom_components/mypyllant/water_heater.py", line 255, in async_set_operation_mode
    await self.coordinator.async_request_refresh_delayed()
  File "/config/custom_components/mypyllant/coordinator.py", line 91, in async_request_refresh_delayed
    self.async_set_updated_data(self.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 517, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 176, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 561, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1073, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/utils.py", line 136, in extra_state_attributes
    if self.zone.general.holiday_remaining
       ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'general'
2024-12-03 12:42:56.849 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Manually updated myVAILLANT data
2024-12-03 12:42:56.851 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140594993658848] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 359, in async_handle_set_operation_mode
    await self.async_set_operation_mode(operation_mode)
  File "/config/custom_components/mypyllant/water_heater.py", line 255, in async_set_operation_mode
    await self.coordinator.async_request_refresh_delayed()
  File "/config/custom_components/mypyllant/coordinator.py", line 91, in async_request_refresh_delayed
    self.async_set_updated_data(self.data)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 517, in async_set_updated_data
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 176, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 561, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1073, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/utils.py", line 136, in extra_state_attributes
    if self.zone.general.holiday_remaining
       ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'general'

```

**Comment by boelle** [comment]
@easyhoo is this still a problem?

**Comment by boelle** [comment]
@signalkraft think we can close this one as @easyhoo  does not have an issue anymore

**Comment by wagnerdom** [comment]
@boelle @signalkraft 
I am experiencing the same output without knowingly performing any operation on my Heatpump:

```
Logger: homeassistant
Quelle: custom_components/mypyllant/utils.py:136
Integration: myVAILLANT ([Dokumentation](https://github.com/signalkraft/mypyllant-component#readme), [Probleme](https://github.com/signalkraft/mypyllant-component/issues))
Erstmals aufgetreten: 15. Februar 2026 um 16:37:05 (25 Vorkommnisse)
Zuletzt protokolliert: 04:37:05
Error doing job: Task exception was never retrieved (task: None)

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 294, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 533, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 200, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 613, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1018, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1163, in _async_write_ha_state
    ) = self.__async_calculate_state()
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1074, in __async_calculate_state
    if extra_state_attributes := self.extra_state_attributes:
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/utils.py", line 136, in extra_state_attributes
    if self.zone.general.holiday_remaining
       ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'general'
```


Sorry for not providing debug output. I disabled the integration for now because my Vaillant-App stopped working. Is this known behaviour for too much traffic on the API? I can't find any errors regarding quota exceeded in HA protocol.
