### ISSUE TITLE
Change of Operationmode leads to error 404

### ISSUE THREAD

**Issue by SebastianDyck** [signalkraft/mypyllant-component#26]
Everytime if I change the Operationmode from the Water Heater oder Zone 1 there is only the Errorcode 404. 

I´m using the Version 0.4.0 from the Myvaillant integration.

With the Myvaillant App everything works fine and also the integration notice the Change of the Mode from the App. But if I try to change it by the Integration it's not working.

[548056349504] 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/9e9c94fc-5036-4b0d-bc1d-d95d07a49ce0/domesticHotWater/255/operationMode')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 227, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2006, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/mypyllant/water_heater.py", line 152, in async_set_operation_mode
    await self.coordinator.api.set_domestic_hot_water_operation_mode(
  File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 479, in set_domestic_hot_water_operation_mode
    return await self.aiohttp_session.post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/9e9c94fc-5036-4b0d-bc1d-d95d07a49ce0/domesticHotWater/255/operationMode')

**Comment by signalkraft** [comment]
Please try the latest beta release and let me know if that works. https://hacs.xyz/docs/faq/beta/

**Comment by earthjumper** [comment]
No, it does not work. The other control options also bring 404 errors.

**Comment by signalkraft** [comment]
Can you turn on [debug logging](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and post the error messages?

**Comment by earthjumper** [comment]
I have created several files. "export.txt" contains the "api.get_system" information. The others are the respective set commands.
[myPyllant-debug.zip](https://github.com/signalkraft/mypyllant-component/files/12642786/myPyllant-debug.zip)

**Comment by signalkraft** [comment]
Thanks for posting debug logs. I deleted your post, since it contained access tokens.

You're still running an older version, you need the latest beta. Make sure you have https://github.com/signalkraft/mypyllant-component/releases/tag/v0.5.0b1 installed and Home Assistant is restarted. If you're using the underlying library directly, https://github.com/signalkraft/myPyllant/releases/tag/v0.5.1 should work

**Comment by earthjumper** [comment]
Thank you very much, that was the problem. Now it works again.
