### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by pnm1977** [signalkraft/mypyllant-component#35]
### Before submitting a new issue

- [Y ] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [Y] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [Y] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description
From 02:55 this morning the data from my ASHP appeared to be active but my automations failed. 

The automation running was climate.set HVAC mode to Auto through a script and has been used on many occasions before. After trying to manually call it a few times I reloaded the integration and all the data points changed as if they had been stuck for a few hours. I then called the script again and it worked. I checked the logs and found one from 02:55.
Since then I have some data points that are updating but I'm not receiving anything for climate.zone1 or sensor.heating_state_in_zone_1. They're still stuck as they were at 02:55.

### Logs

Logger: homeassistant
Source: custom_components/mypyllant/binary_sensor.py:59
Integration: myVAILLANT ([documentation](https://github.com/signalkraft/mypyllant-component#readme), [issues](https://github.com/signalkraft/issues))
First occurred: 02:55:54 (63 occurrences)
Last logged: 06:01:54

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 218, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/mypyllant/binary_sensor.py", line 124, in is_on
    return self.system.has_diagnostic_trouble_codes
           ^^^^^^^^^^^
  File "/config/custom_components/mypyllant/binary_sensor.py", line 59, in system
    return self.coordinator.data[self.system_index]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

**Comment by pnm1977** [comment]
I restarted the gateway after an hour and it fixed the data issue. Therefore, marking issue as closed.
