### ISSUE TITLE
Daily energy consumption totals incorrect

### ISSUE THREAD

**Issue by ccle610** [signalkraft/mypyllant-component#40]
### Before submitting a new issue

- [X ] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [X ] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [ ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

The totals are reset to zero at 0:30.
No more values are recorded until 1:30 am.
The values from 0:00 to 1:30 are lost for the day. 
As a test, the system was set to standby during this time, then the values fit.

### Logs

```
The problem cannot be recorded in log files
```

**Comment by signalkraft** [comment]
The values aren't recorded incrementally, like you're describing.

The API returns the totals for the current day, so every hour (when the totals are updated by the integration) I just get the latest total value. AFAIK there is no way to miss any energy values this way. But there may well be something wrong with timezones, or the way the values get reset within Home Assistant. I'm using [total_increasing](https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes) for the energy sensors.

I may be able to help, if you can provide more information (screenshots comparing the vaillant app and what you're seeing in HA).

**Comment by ccle610** [comment]
![HA_Energy](https://github.com/signalkraft/mypyllant-component/assets/130834305/08e70444-e42a-47de-8496-33f46ce8690a)
![MyVaillant](https://github.com/signalkraft/mypyllant-component/assets/130834305/fd10a990-395f-4c65-8e1d-71326ebb0809)

Thx for answering . . . and ok, I'll understood the Problem now ;-)
Today the HP was not set to standby, so the difference is clearly visible on the Screenshots attached.
I stay in Germany MEZ: UTC+1 and indeed, the gap is smaller since Wintertime startet. Formaly the consumption totals startet app. 3:00 AM - There is no settings in "myVaillant App" to set Timezone - but Germany was selected when I start the App first time

**Comment by rapton** [comment]
I have also a problem in the logs. In Home Assistant it stop working at 00:35 - Happy New Year ;) 
The app says 0 value. I think this is the problem and why the state is "unknown". 

Thanks for the great integration!

![Bild 01 01 24 um 01 13](https://github.com/signalkraft/mypyllant-component/assets/4056154/2042e5a7-72eb-4dfd-a519-4213e2b0f136)

![Bildschirmfoto 2024-01-01 um 01 14 05](https://github.com/signalkraft/mypyllant-component/assets/4056154/5640cf32-1dd5-4bbb-9e77-2b0c59c37a58)

`2024-01-01 00:53:59.673 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform mypyllant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 754, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1025, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 501, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/sensor.py", line 776, in native_value
    return round(self.heat_energy_generated / self.energy_consumed, 1)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero
2024-01-01 00:53:59.764 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mypyllant platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 369, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 754, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1025, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 501, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/sensor.py", line 776, in native_value
    return round(self.heat_energy_generated / self.energy_consumed, 1)
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero`

**Comment by mr-tichyt** [comment]
Hello,

I have exactly the same problem and I think it may really be related to some issue with timezones.

If you check the image below, the first graph is my Shelly Energy meter on the main and the second is what the heat pump says. There is basically nothing else consuming power (<50W). You can see the same graph pattern, but about 4.5 hours delayed. Why? My timezone is CET+1 on both the device and HA.

Any ideas?

![Screenshot 2024-03-06 at 18 25 58](https://github.com/signalkraft/mypyllant-component/assets/40168851/2f939a70-4683-4c0e-947c-368ac770ac8a)

**Comment by mr-tichyt** [comment]
...and also to add, if I check my energy dashboard, the difference between what Shelly measured and what the heat pump reports as consumption differs exactly by what was consumed by the heat pump in the last 4.5 hours of every day...

**Comment by mr-tichyt** [comment]
If you compare the heat pump current power graph with flow temperature, does it match or is it also shifted by some time as for me?
The power readings are completely off in my case and I assume it will break the consumption alignment for a day...

**Comment by signalkraft** [comment]
I posted a more thorough explanation about this problem [at the very bottom off this page](https://signalkraft.com/mypyllant-component/#energy-efficiency-sensors-are-delayed-incomplete-behave-oddly-around-midnight).

**Comment by TilmannBach** [comment]
@signalkraft thanks very much for this detailed explanation on the docs page! this helps me alot to understand the problem.

Am I right: we cannot do something against this problem? Is there a discussion at Vaillant or in HomeAssistant to upvote?

**Comment by ccle610** [comment]
So I think, there is nothing to do here.
I will close this Issue for this reason.
Thank you for explaining, Signalkraft!

**Comment by 0la1** [comment]
Hi everyone,

from what I can read on this issue is that there are discrapancies when considering the energy consumption on a specific period of time (i.e. per day). 
Would this also effect "manual" meter helper who just have increasing totals? Because they seem to have the same issue with increasing differences.

**Comment by boelle** [comment]
@ccle610 do you still have issues?

**Comment by ccle610** [comment]
Due to the frequent problems with the Vaillant API, I have unfortunately abandoned this solution and am now very satisfied with the eBus adapter and an additional electricity meter. However, the MQTT requires a lot of configuration work, so Signalkraft is a really great solution.

**Comment by boelle** [comment]
@signalkraft poke

**Comment by Breina** [comment]
@signalkraft This issue can be closed.
