### ISSUE TITLE
Doesn´t work with APP Migo that is different that Migo Link and MyVaillant

### ISSUE THREAD

**Issue by srtxema** [signalkraft/mypyllant-component#42]
### Before submitting a new issue

- [ X] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [ X] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [ X] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description
Im using Migo APP in iPhone to manage my Saunier Duval sensor. I configure correctly myvaillant integration identified Saunier Duval option but it is empty, no devices added.

### Logs

2023-11-05 15:32:47.141 DEBUG (MainThread) [myPyllant.api] Got response []
2023-11-05 15:32:47.141 DEBUG (MainThread) [custom_components.mypyllant] Finished fetching myVAILLANT data in 0.087 seconds (success: True)
2023-11-05 15:32:47.142 WARNING (MainThread) [custom_components.mypyllant.binary_sensor] No system data, skipping binary sensors
2023-11-05 15:32:47.143 WARNING (MainThread) [custom_components.mypyllant.sensor] No system data, skipping sensors
2023-11-05 15:32:47.143 DEBUG (MainThread) [custom_components.mypyllant.sensor] Daily data: {}
2023-11-05 15:32:47.143 WARNING (MainThread) [custom_components.mypyllant.sensor] No daily data, skipping sensors
2023-11-05 15:32:47.143 WARNING (MainThread) [custom_components.mypyllant.climate] No system data, skipping climate
2023-11-05 15:32:47.143 WARNING (MainThread) [custom_components.mypyllant.water_heater] No system data, skipping water heater

**Comment by signalkraft** [comment]
Thanks for the logs, I removed most of them since they contained session data. The important bit is that there is no system data being returned, so no devices are added. You could try [generating test data](https://signalkraft.com/mypyllant-component/3-contributing/#contributing-test-data) and attaching it to this issue.

**Comment by srtxema** [comment]
it has generate a claims.json file empty.

i received this messages error when generate the test data with docker. 
i have choose sdbg like brand

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/build/src/myPyllant/tests/generate_test_data.py", line 202, in <module>
    asyncio.run(main(args.user, args.password, args.brand, args.country))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/build/src/myPyllant/tests/generate_test_data.py", line 81, in main
    control_identifier_url = f"{API_URL_BASE}/systems/{claims[0]['systemId']}/meta-info/control-identifier"
                                                       ~~~~~~^^^
IndexError: list index out of range

**Comment by signalkraft** [comment]
Apparently no systems are available on the myVAILLANT API with your user account. I fixed the `IndexError`, but unfortunately there sill won't be any data available. You may be on an unsupported version of the app. Have you had to migrate to a newer version, yet?

**Comment by srtxema** [comment]
This is my app. is the official app of vaillant for migo thermostat. They said me that is the app i have used
https://apps.apple.com/es/app/migo-your-heating-assistant/id1023682652

in the website of my thermostat is the app that the recommended too
https://www.saunierduval.es/para-el-usuario/productos/migo-24960.html

**Comment by Spanishu** [comment]
I have just tried to install the Home Assistant integration. I am using the same app as @srtxema is using. 
Reset the password on Migo just to be 100% sure
I am getting that Authorisation is not possible. 
I have selected SaunierDuval & Country Spain

**Comment by Margriko** [comment]
This is the integration which works fine with MiGo (not Link): https://github.com/MislavMandaric/home-assistant-vaillant-vsmart

**Comment by signalkraft** [comment]
Thanks for posting that link, I'll close this then.
