### ISSUE TITLE
Duplicate VR 921 Device in v0.6.0

### ISSUE THREAD

**Issue by pnm1977** [signalkraft/mypyllant-component#48]
### Before submitting a new issue

- [y] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [y] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [y] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

The new v0.6.0 downloaded fine but I've ended up with 2 VR 921 device. One of them only contains an unavailable sensor.home_vr_921 which also has a warning stating "This entity is no longer being provided by the mypyllant integration. If the entity is no longer in use, delete it in settings". 

### Logs
**Log 1 -**
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/mypyllant/sensor.py:726
Integration: myVAILLANT (documentation, issues)
First occurred: 17:15:16 (1 occurrences)
Last logged: 17:15:16

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 749, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 501, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/sensor.py", line 775, in native_value
    if self.energy_consumed:
       ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/sensor.py", line 736, in energy_consumed
    for v in self.device_data_list
             ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/sensor.py", line 726, in device_data_list
    return self.coordinator.data[self.system_id]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Log 2 -** 
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/mypyllant/binary_sensor.py:59
Integration: myVAILLANT (documentation, issues)
First occurred: 10:47:45 (5 occurrences)
Last logged: 17:15:17

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 749, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 218, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/mypyllant/binary_sensor.py", line 92, in is_on
    return self.system.has_diagnostic_trouble_codes
           ^^^^^^^^^^^
  File "/config/custom_components/mypyllant/binary_sensor.py", line 59, in system
    return self.coordinator.data[self.system_index]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

**Comment by nukleuz80** [comment]
I think i have the same issue...

![image](https://github.com/signalkraft/mypyllant-component/assets/43496030/270cf784-f397-40af-8f99-87839fdd0375)

**Comment by signalkraft** [comment]
Could you try again in the latest release? Devices and entities are named differently, so you'll get more duplicates, but you should no longer have two active devices with the same name.

**Comment by signalkraft** [comment]
You can delete the integration and add it again. Old historical values should stay, and outdated devices will be deleted. Still, probably best to create a backup before in Settings > System > Backups.
