### ISSUE TITLE
Make current_room_temperature optional

### ISSUE THREAD

**Issue by signalkraft** [signalkraft/mypyllant-component#6]
Thank you. Now the log in works perfectly.
Unfortunately no devices are listed in the integration.

I report some errors:

Logger: custom_components.mypyllant
Source: custom_components/mypyllant/__init__.py:139
Integration: myVAILLANT (documentation, issues)
First occurred: 8 marzo 2023 alle ore 23:26:08 (4 occurrences)
Last logged: 21:59:45

Unexpected error fetching myVAILLANT data: 1 validation error for Zone current_room_temperature field required (type=value_error.missing)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/mypyllant/__init__.py", line 139, in _async_update_data
    data = [
  File "/config/custom_components/mypyllant/__init__.py", line 139, in <listcomp>
    data = [
  File "/usr/local/lib/python3.10/site-packages/myPyllant/api.py", line 200, in get_systems
    system = System(
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 114, in __init__
    self.zones = [Zone(system_id=self.id, **z) for z in self._raw_zones]
  File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 114, in <listcomp>
    self.zones = [Zone(system_id=self.id, **z) for z in self._raw_zones]
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Zone
current_room_temperature
  field required (type=value_error.missing)

And the other one:

Logger: homeassistant.components.binary_sensor
Source: custom_components/mypyllant/binary_sensor.py:32
Integration: Sensore binario (documentation, issues)
First occurred: 8 marzo 2023 alle ore 23:26:09 (4 occurrences)
Last logged: 21:59:46

Error while setting up mypyllant platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mypyllant/binary_sensor.py", line 32, in async_setup_entry
    for index, system in enumerate(coordinator.data):
TypeError: 'NoneType' object is not iterable

Any help?

Thanks

_Originally posted by @MP14588 in https://github.com/signalkraft/mypyllant-component/issues/4#issuecomment-1462831093_

**Comment by signalkraft** [comment]
@MP14588 please try out the latest release. I made the field optional, that your system doesn't seem to have!

**Comment by MP14588** [comment]
Fantastic! Now every woks fine, 4 devices and 30 entities found!
Thank you for your time!
Cheers.
