### ISSUE TITLE
404 error setting any DHW or heating mode

### ISSUE THREAD

**Issue by JonSilver** [signalkraft/mypyllant-component#60]
### Before submitting a new issue

- [x] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Setting any DHW or heating mode, this error occurs...

Either the API endpoints changed, or 404 is their strange way of telling me my API key is no longer valid.

Reloading the integration makes no difference.

### Logs

```

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 09:33:48 (3 occurrences)
Last logged: 09:34:53

[281469336131008] 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/xxxxxx/tli/domestic-hot-water/255/boost')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/mypyllant/water_heater.py", line 168, in async_set_operation_mode
    await self.coordinator.api.boost_domestic_hot_water(
  File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 641, in boost_domestic_hot_water
    return await self.aiohttp_session.post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 689, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1059, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/xxxxxx/tli/domestic-hot-water/255/boost')

```

**Comment by JonSilver** [comment]
I discovered the app was also unable to connect, and was complaining about my gateway being offline. So I restarted the MyVaillant Connect box and both the app and integration are now working once again.

Sorry for the false alarm. Leaving this here in case it helps anyone else who experiences the same thing.
