### ISSUE TITLE
integration with MiGo Link for Protherm (Duval)

### ISSUE THREAD

**Issue by augard** [signalkraft/mypyllant-component#78]
### Problem description

I am using new app MiGo Link for Protherm heat pump. It was successfully added, but it looks like it can't parse response for my heating.

### Logs

```
2024-01-08 16:17:42.915 DEBUG (MainThread) [custom_components.mypyllant] Finished fetching myVAILLANT data in 0.635 seconds (success: False)
2024-01-08 16:17:42.916 DEBUG (MainThread) [custom_components.mypyllant] Refreshing DailyDataCoordinator
2024-01-08 16:17:42.916 DEBUG (MainThread) [custom_components.mypyllant] Starting async update data for DailyDataCoordinator
2024-01-08 16:17:42.916 DEBUG (MainThread) [custom_components.mypyllant] Waiting 119s until token refresh for lfoldyna@gmail.com
2024-01-08 16:17:42.916 DEBUG (MainThread) [custom_components.mypyllant] Getting data from 2024-01-08 00:00:00 to 2024-01-09 00:00:00
2024-01-08 16:17:42.926 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='GET', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/homes'), headers=<CIMultiDict('Authorization': 'Bearer', 'x-app-identifier': 'VAILLANT', 'Accept-Language': 'en-GB', 'Accept': 'application/json, text/plain, */*', 'x-client-locale': 'en-GB', 'x-idm-identifier': 'KEYCLOAK', 'ocp-apim-subscription-key': '1e0a2f3511fb4c5bbb1c7f9fedd20b1c', 'User-Agent': 'okhttp/4.9.2', 'Connection': 'keep-alive')>)
2024-01-08 16:17:42.973 DEBUG (MainThread) [myPyllant.api] Got response [{"homeName":"Home","address":{"street":"Address","extension":null,"city":"Praha","postalCode":"000 00","countryCode":"CZ"},"serialNumber":"some serial","systemId":"some system id","productMetadata":{"productType":"SR940F","productionYear":"23","productionWeek":"02","articleNumber":"0020292013"},"state":"CLAIMED","migrationState":null,"firmware":{"version":null,"updateEnabled":false,"updateRequired":false},"nomenclature":"SR 940f","cag":true,"countryCode":"CZ","productInformation":"SR940F","firmwareVersion":null}]
2024-01-08 16:17:42.975 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='GET', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/b70ae729-2e29-49ca-87ec-499502c68659/meta-info/time-zone'), headers=<CIMultiDict('Authorization': 'Bearer', 'x-app-identifier': 'VAILLANT', 'Accept-Language': 'en-GB', 'Accept': 'application/json, text/plain, */*', 'x-client-locale': 'en-GB', 'x-idm-identifier': 'KEYCLOAK', 'ocp-apim-subscription-key': '1e0a2f3511fb4c5bbb1c7f9fedd20b1c', 'User-Agent': 'okhttp/4.9.2', 'Connection': 'keep-alive')>)
2024-01-08 16:17:43.041 DEBUG (MainThread) [myPyllant.api] Got response {"timeZone":"Europe/Prague"}
2024-01-08 16:17:43.045 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='GET', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/b70ae729-2e29-49ca-87ec-499502c68659/meta-info/control-identifier'), headers=<CIMultiDict('Authorization': 'Bearer', 'x-app-identifier': 'VAILLANT', 'Accept-Language': 'en-GB', 'Accept': 'application/json, text/plain, */*', 'x-client-locale': 'en-GB', 'x-idm-identifier': 'KEYCLOAK', 'ocp-apim-subscription-key': '1e0a2f3511fb4c5bbb1c7f9fedd20b1c', 'User-Agent': 'okhttp/4.9.2', 'Connection': 'keep-alive')>)
2024-01-08 16:17:43.104 DEBUG (MainThread) [myPyllant.api] Got response {"controlIdentifier":"tli"}
2024-01-08 16:17:43.105 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='GET', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/systems/b70ae729-2e29-49ca-87ec-499502c68659/tli'), headers=<CIMultiDict('Authorization': 'Bearer', 'x-app-identifier': 'VAILLANT', 'Accept-Language': 'en-GB', 'Accept': 'application/json, text/plain, */*', 'x-client-locale': 'en-GB', 'x-idm-identifier': 'KEYCLOAK', 'ocp-apim-subscription-key': '1e0a2f3511fb4c5bbb1c7f9fedd20b1c', 'User-Agent': 'okhttp/4.9.2', 'Connection': 'keep-alive')>)
2024-01-08 16:17:43.164 DEBUG (MainThread) [myPyllant.api] Got response {"state":{"system":{"outdoorTemperature":-5.8242188,"systemWaterPressure":2.3},"zones":[{"index":0,"desiredRoomTemperatureSetpointHeating":21.5,"desiredRoomTemperatureSetpoint":21.5,"currentRoomTemperature":21.875,"currentRoomHumidity":34.0,"currentSpecialFunction":"NONE","heatingState":"IDLE","isManualCoolingActive":false,"summerCutOffActive":false}],"circuits":[{"index":0,"circuitState":"STANDBY","currentCircuitFlowTemperature":42.0,"calculatedEnergyManagerState":"HEATING_STANDBY"}],"dhw":[{"index":255,"currentSpecialFunction":"REGULAR","currentDhwTemperature":48.5}]},"properties":{"system":{"controllerType":"VRC720","systemScheme":1,"backupHeaterType":"CONDENSING","backupHeaterAllowedFor":"DHW_AND_HEATING","moduleConfigurationVR71":3,"energyProvidePowerCutBehavior":"DISABLE_HEATPUMP_AND_BACKUP_HEATER"},"zones":[{"index":0,"isCoolingAllowed":false,"associatedCircuitIndex":0}],"circuits":[{"index":0,"mixerCircuitTypeExternal":"HEATING","isCoolingAllowed":false}],"dhw":[{"index":255,"minSetpoint":35.0,"maxSetpoint":70.0}]},"configuration":{"system":{"alternativePoint":-21.0,"heatingCircuitBivalencePoint":-7.0,"dhwBivalencePoint":-7.0,"automaticCoolingOnOff":false,"adaptiveHeatingCurve":false,"dhwMaximumLoadingTime":60,"dhwHysteresis":5.0,"dhwFlowSetpointOffset":25.0,"continuousHeatingRoomSetpoint":20.0,"maxFlowSetpointHpError":25.0,"dhwMaximumTemperature":80.0,"maximumPreheatingTime":0,"paralellTankLoadingAllowed":false},"zones":[{"index":0,"general":{"name":"Dum"},"heating":{"operationModeHeating":"TIME_CONTROLLED","setBackTemperature":21.0,"manualModeSetpointHeating":21.0,"timeProgramHeating":{"metaInfo":{"minSlotsPerDay":0,"maxSlotsPerDay":12,"setpointRequiredPerSlot":true},"monday":[{"startTime":390,"endTime":1410,"setpoint":21.5}],"tuesday":[{"startTime":390,"endTime":1410,"setpoint":21.5}],"wednesday":[{"startTime":390,"endTime":1410,"setpoint":21.5}],"thursday":[{"startTime":390,"endTime":1410,"setpoint":21.5}],"friday":[{"startTime":390,"endTime":1410,"setpoint":21.5}],"saturday":[{"startTime":450,"endTime":1410,"setpoint":21.5}],"sunday":[{"startTime":450,"endTime":1410,"setpoint":21.5}]}},"cooling":{"operationModeCooling":"TIME_CONTROLLED","manualModeSetpointCooling":24.0}}],"circuits":[{"index":0,"heatingCurve":1.1,"heatingFlowTemperatureMinimumSetpoint":35.0,"heatingFlowTemperatureMaximumSetpoint":90.0,"heatDemandLimitedByOutsideTemperature":21.0,"coolingFlowTemperatureMinimumSetpoint":20.0,"setBackModeEnabled":true,"roomTemperatureControlMode":"NON"}],"dhw":[{"index":255,"operationModeDhw":"TIME_CONTROLLED","tappingSetpoint":48.0,"timeProgramDhw":{"metaInfo":{"minSlotsPerDay":0,"maxSlotsPerDay":3,"setpointRequiredPerSlot":false},"monday":[{"startTime":420,"endTime":1260}],"tuesday":[{"startTime":420,"endTime":1260}],"wednesday":[{"startTime":420,"endTime":1260}],"thursday":[{"startTime":420,"endTime":1260}],"friday":[{"startTime":420,"endTime":1260}],"saturday":[{"startTime":420,"endTime":1260}],"sunday":[{"startTime":420,"endTime":1260}]}}]}}
2024-01-08 16:17:43.166 DEBUG (MainThread) [myPyllant.api] Starting request TraceRequestStartParams(method='GET', url=URL('https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/emf/v2/b70ae729-2e29-49ca-87ec-499502c68659/currentSystem'), headers=<CIMultiDict('Authorization': 'Bearer', 'x-app-identifier': 'VAILLANT', 'Accept-Language': 'en-GB', 'Accept': 'application/json, text/plain, */*', 'x-client-locale': 'en-GB', 'x-idm-identifier': 'KEYCLOAK', 'ocp-apim-subscription-key': '1e0a2f3511fb4c5bbb1c7f9fedd20b1c', 'User-Agent': 'okhttp/4.9.2', 'Connection': 'keep-alive')>)
2024-01-08 16:17:43.232 DEBUG (MainThread) [myPyllant.api] Got response {"system_type":"UNKNOWN","has_emf_capable_devices":false,"primary_heat_generator":null,"secondary_heat_generators":[],"electric_backup_heater":null,"solar_station":null,"ventilation":null,"gateway":null}
2024-01-08 16:17:43.236 DEBUG (MainThread) [myPyllant.models] Creating related models from state: {'brand': 'sdbg', 'home': Home(extra_fields={}, country_code='CZ', timezone=tzfile('/usr/share/zoneinfo/Europe/Prague'), nomenclature='SR 940f', serial_number='some serial', state='CLAIMED', system_id='some system id', home_name='Home', address={'street': 'Address', 'extension': None, 'city': 'Praha', 'postal_code': '000 00', 'country_code': 'CZ'}, product_information='SR940F', migration_state=None, cag=True, firmware_version=None, firmware={'version': None, 'update_enabled': False, 'update_required': False}, product_metadata={'product_type': 'SR940F', 'production_year': '23', 'production_week': '02', 'article_number': '0020292013'}), 'timezone': tzfile('/usr/share/zoneinfo/Europe/Prague'), 'connected': None, 'diagnostic_trouble_codes': None, 'mpc': {}, 'current_system': {'system_type': 'UNKNOWN', 'has_emf_capable_devices': False, 'primary_heat_generator': None, 'secondary_heat_generators': [], 'electric_backup_heater': None, 'solar_station': None, 'ventilation': None, 'gateway': None}, 'state': {'system': {'outdoor_temperature': -5.8242188, 'system_water_pressure': 2.3}, 'zones': [{'index': 0, 'desired_room_temperature_setpoint_heating': 21.5, 'desired_room_temperature_setpoint': 21.5, 'current_room_temperature': 21.875, 'current_room_humidity': 34.0, 'current_special_function': 'NONE', 'heating_state': 'IDLE', 'is_manual_cooling_active': False, 'summer_cut_off_active': False}], 'circuits': [{'index': 0, 'circuit_state': 'STANDBY', 'current_circuit_flow_temperature': 42.0, 'calculated_energy_manager_state': 'HEATING_STANDBY'}], 'dhw': [{'index': 255, 'current_special_function': 'REGULAR', 'current_dhw_temperature': 48.5}]}, 'properties': {'system': {'controller_type': 'VRC720', 'system_scheme': 1, 'backup_heater_type': 'CONDENSING', 'backup_heater_allowed_for': 'DHW_AND_HEATING', 'module_configuration_v_r71': 3, 'energy_provide_power_cut_behavior': 'DISABLE_HEATPUMP_AND_BACKUP_HEATER'}, 'zones': [{'index': 0, 'is_cooling_allowed': False, 'associated_circuit_index': 0}], 'circuits': [{'index': 0, 'mixer_circuit_type_external': 'HEATING', 'is_cooling_allowed': False}], 'dhw': [{'index': 255, 'min_setpoint': 35.0, 'max_setpoint': 70.0}]}, 'configuration': {'system': {'alternative_point': -21.0, 'heating_circuit_bivalence_point': -7.0, 'dhw_bivalence_point': -7.0, 'automatic_cooling_on_off': False, 'adaptive_heating_curve': False, 'dhw_maximum_loading_time': 60, 'dhw_hysteresis': 5.0, 'dhw_flow_setpoint_offset': 25.0, 'continuous_heating_room_setpoint': 20.0, 'max_flow_setpoint_hp_error': 25.0, 'dhw_maximum_temperature': 80.0, 'maximum_preheating_time': 0, 'paralell_tank_loading_allowed': False}, 'zones': [{'index': 0, 'general': {'name': 'Dum'}, 'heating': {'operation_mode_heating': 'TIME_CONTROLLED', 'set_back_temperature': 21.0, 'manual_mode_setpoint_heating': 21.0, 'time_program_heating': {'meta_info': {'min_slots_per_day': 0, 'max_slots_per_day': 12, 'setpoint_required_per_slot': True}, 'monday': [{'start_time': 390, 'end_time': 1410, 'setpoint': 21.5}], 'tuesday': [{'start_time': 390, 'end_time': 1410, 'setpoint': 21.5}], 'wednesday': [{'start_time': 390, 'end_time': 1410, 'setpoint': 21.5}], 'thursday': [{'start_time': 390, 'end_time': 1410, 'setpoint': 21.5}], 'friday': [{'start_time': 390, 'end_time': 1410, 'setpoint': 21.5}], 'saturday': [{'start_time': 450, 'end_time': 1410, 'setpoint': 21.5}], 'sunday': [{'start_time': 450, 'end_time': 1410, 'setpoint': 21.5}]}}, 'cooling': {'operation_mode_cooling': 'TIME_CONTROLLED', 'manual_mode_setpoint_cooling': 24.0}}], 'circuits': [{'index': 0, 'heating_curve': 1.1, 'heating_flow_temperature_minimum_setpoint': 35.0, 'heating_flow_temperature_maximum_setpoint': 90.0, 'heat_demand_limited_by_outside_temperature': 21.0, 'cooling_flow_temperature_minimum_setpoint': 20.0, 'set_back_mode_enabled': True, 'room_temperature_control_mode': 'NON'}], 'dhw': [{'index': 255, 'operation_mode_dhw': 'TIME_CONTROLLED', 'tapping_setpoint': 48.0, 'time_program_dhw': {'meta_info': {'min_slots_per_day': 0, 'max_slots_per_day': 3, 'setpoint_required_per_slot': False}, 'monday': [{'start_time': 420, 'end_time': 1260}], 'tuesday': [{'start_time': 420, 'end_time': 1260}], 'wednesday': [{'start_time': 420, 'end_time': 1260}], 'thursday': [{'start_time': 420, 'end_time': 1260}], 'friday': [{'start_time': 420, 'end_time': 1260}], 'saturday': [{'start_time': 420, 'end_time': 1260}], 'sunday': [{'start_time': 420, 'end_time': 1260}]}}]}, 'id': 'b70ae729-2e29-49ca-87ec-499502c68659'}
2024-01-08 16:17:43.242 ERROR (MainThread) [custom_components.mypyllant] Unexpected error fetching myVAILLANT data: missing value for field "is_active"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/dacite/core.py", line 72, in from_dict
    value = get_default_value_for_field(field, field_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dacite/dataclasses.py", line 22, in get_default_value_for_field
    raise DefaultValueNotFoundError()
dacite.dataclasses.DefaultValueNotFoundError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/__init__.py", line 380, in _async_update_data
    async for system in await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 321, in get_systems
    system = System.from_api(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 403, in from_api
    system.zones = [
                   ^
  File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 404, in 
    Zone.from_api(system_id=system.id, timezone=system.timezone, **z)
  File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 293, in from_api
    return super().from_api(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 137, in from_api
    return from_dict(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/dacite/core.py", line 76, in from_dict
    raise MissingValueError(field.name)
dacite.exceptions.MissingValueError: missing value for field "is_active"
2024-01-08 16:17:43.265 DEBUG (MainThread) [custom_components.mypyllant] Finished fetching myVAILLANT data in 0.350 seconds (success: False)
```

**Comment by signalkraft** [comment]
Should be addressed in the next release. Could you try and run the [test data service](https://signalkraft.com/mypyllant-component/3-contributing/#contributing-test-data) and attach the results here? That way I could add test cases for your setup.

**Comment by signalkraft** [comment]
Can you check if it works with [this pre-release](https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.2b0) please? You need to enable beta versions for this integration in HACS.

**Comment by signalkraft** [comment]
I'll close this for now, but feel free to reopen when you're able to test it and it doesn't work.
