### ISSUE TITLE
No parameter readings and updates

### ISSUE THREAD

**Issue by szflo** [signalkraft/mypyllant-component#90]
### Before submitting a new issue

- [x] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

The update of all parameters (temp, humidity, etc) does not work. The last working version is 0.7.0. I have tested all subsequent betas and after the update all value readings stand still. Returning to version 0.7.0 resumes correct parameter readings. I am using "Ventilation VAR 360/4" which since v0.7.0 does not work and I suspect this is the problem.
Last tested version is: v0.7.2b4

### Logs

[ha-myp.log](https://github.com/signalkraft/mypyllant-component/files/14154710/ha-myp.log)

```


Logger: homeassistant
Source: custom_components/mypyllant/climate.py:588
Integration: myVAILLANT (documentation, issues)
First occurred: 01:11:12 (4 occurrences)
Last logged: 01:14:21

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 295, in state
    hvac_mode = self.hvac_mode
                ^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/climate.py", line 588, in hvac_mode
    return [
           ^
IndexError: list index out of range

```

**Comment by signalkraft** [comment]
Could you attach [test data](https://signalkraft.com/mypyllant-component/3-contributing/#contributing-test-data) with the latest pre-release installed? Calling the service should hopefully still work.

**Comment by szflo** [comment]
[ha_vaillant.tar.gz](https://github.com/signalkraft/mypyllant-component/files/14156905/ha_vaillant.tar.gz)

^ test data

I can update data by clicking on "update data" in hacs integration. After installing a version newer than 0.7.0, the data is not updated. Ventilation integration entity does not work from v0.7.0. Please let me know what I can do to investigate this problem and help to improve integration. Thank you!

**Comment by signalkraft** [comment]
Thanks, could you please test the latest pre-release?

**Comment by szflo** [comment]
Pre-release v0.7.2b6 works great! Thanks.
