### ISSUE TITLE
no entities / ecoCOMPACT VSC 206/4-5 150 LL

### ISSUE THREAD

**Issue by cornettonuss** [signalkraft/mypyllant-component#94]
- [X] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [X] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant (I'am using v0.7.3b0)
- [X] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

Hi everyone,
i just upgraded my gateway to use the new MyVaillant app which is working fine now. Also the login within the integration is working.
However, I'am not able to get any information out of the integration. Zero entities are shown.
I could identify two issues, I attached the debug output for both of them below.

My heating setup:
- ecoCOMPACT VSC 206/4-5 150 LL
- Two heating circuits

Best regards

(anonymized the uuid in this one)
```
WARNING
Logger: myPyllant.api
Source: /usr/local/lib/python3.11/site-packages/myPyllant/api.py:1027
First occurred: 15:39:48 (1 occurrences)
Last logged: 15:39:48

Could not get RTS data
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 1022, in get_rts
    response = await self.aiohttp_session.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 691, in _request
    await raise_for_status(resp)
  File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 102, in on_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1060, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Resource Not Found', url=URL('https://api.vaillant-group.com/service-connected-control/vrc700/v1/rts/ef4b0740-a526-4300-976d-123456789012/devices')
```

```
ERROR
Logger: custom_components.mypyllant
Source: helpers/update_coordinator.py:300
Integration: myVAILLANT (documentation, issues)
First occurred: 15:39:48 (2 occurrences)
Last logged: 15:39:49

Unexpected error fetching myVAILLANT data: 'SET_BACK' is not a valid ZoneHeatingOperatingModeVRC700
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/__init__.py", line 350, in _async_update_data
    data = [
           ^
  File "/config/custom_components/mypyllant/__init__.py", line 350, in <listcomp>
    data = [
           ^
  File "/usr/local/lib/python3.11/site-packages/myPyllant/api.py", line 386, in get_systems
    system = System.from_api(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 541, in from_api
    system.zones = [
                   ^
  File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 542, in <listcomp>
    Zone.from_api(
  File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 382, in from_api
    kwargs["heating"] = ZoneHeating.from_api(
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/myPyllant/models.py", line 290, in from_api
    kwargs["operation_mode_heating"] = ZoneHeatingOperatingModeVRC700(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 1135, in __new__
    raise ve_exc
ValueError: 'SET_BACK' is not a valid ZoneHeatingOperatingModeVRC700
```

**Comment by signalkraft** [comment]
Could you try the latest pre-release?

**Comment by cornettonuss** [comment]
Hi @signalkraft,
the latest pre-release works fine. I can see all relevant entities now.
Thank you very much!
